export const CLOUDFLARE_ACCESS_ERROR_CODES = {
  UNAVAILABLE: "CLOUDFLARE_ACCESS_UNAVAILABLE",
  RESOURCE_ID_CONFLICT: "CLOUDFLARE_ACCESS_RESOURCE_ID_CONFLICT",
  NOT_FOUND: "CLOUDFLARE_ACCESS_NOT_FOUND",
  FORBIDDEN: "CLOUDFLARE_ACCESS_FORBIDDEN",
  IN_USE: "CLOUDFLARE_ACCESS_IN_USE",
  REVISION_CONFLICT: "CLOUDFLARE_ACCESS_REVISION_CONFLICT",
  REVISION_EXHAUSTED: "CLOUDFLARE_ACCESS_REVISION_EXHAUSTED",
} as const;

export type CloudflareAccessErrorCode =
  (typeof CLOUDFLARE_ACCESS_ERROR_CODES)[keyof typeof CLOUDFLARE_ACCESS_ERROR_CODES];
