export const CLOUDFLARE_ACCESS_ERROR_CODES = {
  UNAVAILABLE: "CLOUDFLARE_ACCESS_UNAVAILABLE",
  NOT_FOUND: "CLOUDFLARE_ACCESS_NOT_FOUND",
  IN_USE: "CLOUDFLARE_ACCESS_IN_USE",
  REVISION_CONFLICT: "CLOUDFLARE_ACCESS_REVISION_CONFLICT",
} as const;

export type CloudflareAccessErrorCode =
  (typeof CLOUDFLARE_ACCESS_ERROR_CODES)[keyof typeof CLOUDFLARE_ACCESS_ERROR_CODES];
