export const SSH_ERROR_CODES = {
  UNAVAILABLE: "SSH_UNAVAILABLE",
  AGENT_UNAVAILABLE: "SSH_AGENT_UNAVAILABLE",
  INVALID_INPUT: "SSH_INVALID_INPUT",
  SAVE_ATTEMPT_RESOLVED: "SSH_SAVE_ATTEMPT_RESOLVED",
  INVALID_HOST: "SSH_INVALID_HOST",
  CONNECTION_NOT_FOUND: "SSH_CONNECTION_NOT_FOUND",
  GENERATION_CONFLICT: "SSH_GENERATION_CONFLICT",
  CREDENTIAL_NOT_FOUND: "SSH_CREDENTIAL_NOT_FOUND",
  CREDENTIAL_IN_USE: "SSH_CREDENTIAL_IN_USE",
  CREDENTIAL_REVISION_CONFLICT: "SSH_CREDENTIAL_REVISION_CONFLICT",
  REVISION_EXHAUSTED: "SSH_REVISION_EXHAUSTED",
  ACCESS_UNAVAILABLE: "CLOUDFLARE_ACCESS_UNAVAILABLE",
  ACCESS_NOT_FOUND: "CLOUDFLARE_ACCESS_NOT_FOUND",
  ACCESS_IN_USE: "CLOUDFLARE_ACCESS_IN_USE",
  ACCESS_REVISION_CONFLICT: "CLOUDFLARE_ACCESS_REVISION_CONFLICT",
} as const;

export type SshErrorCode =
  (typeof SSH_ERROR_CODES)[keyof typeof SSH_ERROR_CODES];
