export const TAILSCALE_ERROR_CODES = {
  NOT_FOUND: "TAILSCALE_NOT_FOUND",
  FORBIDDEN: "TAILSCALE_FORBIDDEN",
  RESOURCE_ID_CONFLICT: "TAILSCALE_RESOURCE_ID_CONFLICT",
  REVISION_CONFLICT: "TAILSCALE_REVISION_CONFLICT",
  REVISION_EXHAUSTED: "TAILSCALE_REVISION_EXHAUSTED",
  IN_USE: "TAILSCALE_IN_USE",
} as const;
export type TailscaleErrorCode =
  (typeof TAILSCALE_ERROR_CODES)[keyof typeof TAILSCALE_ERROR_CODES];
