export const VNC_ERROR_CODES = {
  UNAVAILABLE: "VNC_UNAVAILABLE",
  INVALID_INPUT: "VNC_INVALID_INPUT",
  INVALID_HOST: "VNC_INVALID_HOST",
  INVALID_TRUST: "VNC_INVALID_TRUST",
  CREDENTIAL_NOT_FOUND: "VNC_CREDENTIAL_NOT_FOUND",
  CONNECTION_NOT_FOUND: "VNC_CONNECTION_NOT_FOUND",
  RESOURCE_ID_CONFLICT: "VNC_RESOURCE_ID_CONFLICT",
  CREDENTIAL_IN_USE: "VNC_CREDENTIAL_IN_USE",
  CREDENTIAL_REVISION_CONFLICT: "VNC_CREDENTIAL_REVISION_CONFLICT",
  GENERATION_CONFLICT: "VNC_GENERATION_CONFLICT",
  REVISION_EXHAUSTED: "VNC_REVISION_EXHAUSTED",
  OWNER_CHANGED: "VNC_OWNER_CHANGED",
} as const;

export type VncErrorCode =
  (typeof VNC_ERROR_CODES)[keyof typeof VNC_ERROR_CODES];
