import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import {
  copyFile,
  mkdir,
  mkdtemp,
  readFile,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Client } from "pg";
import postgres from "postgres";
import { applyPendingMigrations } from "./migration-runner";

// Infrastructure boundary: an isolated database exercises the actual generated
// migration frontier, PostgreSQL locks, rollback, constraints and query plans.
const databaseUrl = process.env.DATABASE_URL;
assert.ok(databaseUrl, "DATABASE_URL is required");
const originalDirectory = process.cwd();
const directory = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../src/migrations",
);
const journal = JSON.parse(
  await readFile(join(directory, "meta/_journal.json"), "utf8"),
) as {
  entries: { idx: number; tag: string; when: number }[];
};
const expand = journal.entries.find((e) => {
  return e.tag === "1132_pi_inference_lifecycle";
});
const validate = journal.entries.find((e) => {
  return e.tag === "1133_validate_pi_inference_launch";
});
assert.ok(expand && validate);
const fixture = await mkdtemp(join(tmpdir(), "pi-inference-migration-"));
const migrations = join(fixture, "src/migrations");
const database = `pi_foundation_${randomUUID().replaceAll("-", "")}`;
const adminUrl = new URL(databaseUrl);
adminUrl.pathname = "/postgres";
const url = new URL(adminUrl);
url.pathname = `/${database}`;
const admin = new Client({ connectionString: adminUrl.toString() });
const client = new Client({ connectionString: url.toString() });
await admin.connect();

async function frontier(last: number) {
  const entries = journal.entries.filter((e) => {
    return e.idx <= last;
  });
  await mkdir(join(migrations, "meta"), { recursive: true });
  for (const entry of entries) {
    await copyFile(
      join(directory, `${entry.tag}.sql`),
      join(migrations, `${entry.tag}.sql`),
    );
  }
  // The shortened frontier belongs only to this temporary fixture. Repository
  // journal/snapshots are generated by Drizzle and remain untouched.
  await writeFile(
    join(migrations, "meta/_journal.json"),
    JSON.stringify({ ...journal, entries }),
  );
}

async function apply() {
  const sql = postgres(url.toString(), { max: 1, onnotice: () => {} });
  process.chdir(fixture);
  try {
    await applyPendingMigrations(sql);
  } finally {
    process.chdir(originalDirectory);
    await sql.end();
  }
}

async function constraint() {
  return (
    await client.query<{
      validated: boolean;
    }>(`SELECT convalidated AS validated FROM pg_constraint
    WHERE conrelid = 'agent_runs'::regclass AND conname = 'agent_runs_launch_snapshot_check'`)
  ).rows[0]?.validated;
}

try {
  await admin.query(`CREATE DATABASE "${database}"`);
  await frontier(expand.idx - 1);
  await apply();
  await client.connect();
  // Synthetic metadata matches the refreshed whole-table census, not actual
  // production data or its physical distribution, concurrent load, or latency.
  await client.query(`INSERT INTO agents (id, org_id, owner, name)
    VALUES ('00000000-0000-4000-8000-000000034242', 'foundation-scale', 'foundation-user', 'foundation');
    INSERT INTO agent_sessions (agent_id, org_id, user_id)
    SELECT '00000000-0000-4000-8000-000000034242', 'foundation-scale', 'foundation-user'
    FROM generate_series(1, 71954);
    INSERT INTO agent_runs (session_id, org_id, user_id, prompt, status, trigger_source, autonomy_budget, launch_snapshot)
    SELECT (SELECT id FROM agent_sessions LIMIT 1), 'foundation-scale', 'foundation-user', 'fixture', 'completed', 'web', 0,
      CASE n % 4 WHEN 0 THEN NULL WHEN 1 THEN '{"schemaVersion":1,"framework":"codex","runnerProfile":"vm0/default"}'::jsonb
      WHEN 2 THEN '{"schemaVersion":2,"framework":"pi","runnerProfile":"vm0/default","piMemoryGenerationEnabled":false}'::jsonb
      ELSE '{"schemaVersion":3,"framework":"pi","runnerProfile":"vm0/default"}'::jsonb END
    FROM generate_series(1, 282839) n;
    INSERT INTO conversations (run_id, cli_agent_type, cli_agent_session_id)
    SELECT id, 'pi', id::text FROM agent_runs LIMIT 277397;
    ANALYZE agent_runs; ANALYZE agent_sessions; ANALYZE conversations;`);
  const before = (
    await client.query(
      `SELECT launch_snapshot, count(*)::int AS count FROM agent_runs GROUP BY launch_snapshot ORDER BY launch_snapshot::text`,
    )
  ).rows;
  await frontier(validate.idx);
  await client.query("BEGIN");
  await client.query("LOCK TABLE agent_runs IN ACCESS SHARE MODE");
  try {
    await assert.rejects(apply(), /lock timeout/);
  } finally {
    await client.query("ROLLBACK");
  }
  assert.equal(
    (await client.query("SELECT to_regclass('agent_run_inference') AS name"))
      .rows[0].name,
    null,
  );
  assert.equal(await constraint(), true);
  assert.equal(
    (
      await client.query(
        "SELECT count(*)::int AS n FROM drizzle.__drizzle_migrations WHERE created_at >= $1",
        [expand.when],
      )
    ).rows[0].n,
    0,
  );
  console.log(
    "PASS expand lock timeout rolls back tables, constraint and journal",
  );

  await client.query(
    `ALTER TABLE drizzle.__drizzle_migrations ADD CONSTRAINT foundation_inject_failure CHECK (created_at <> ${validate.when})`,
  );
  const started = performance.now();
  await assert.rejects(apply(), /foundation_inject_failure/);
  console.log(
    `Synthetic expand plus rejected validation: ${Math.round(performance.now() - started)} ms (not a production lock bound)`,
  );
  assert.equal(await constraint(), false);
  assert.equal(
    (await client.query("SELECT count(*)::int AS n FROM agent_run_inference"))
      .rows[0].n,
    0,
  );
  assert.deepEqual(
    (
      await client.query(
        `SELECT launch_snapshot, count(*)::int AS count FROM agent_runs GROUP BY launch_snapshot ORDER BY launch_snapshot::text`,
      )
    ).rows,
    before,
  );
  // Even NOT VALID enforces both old writers and the strict new shape on writes.
  const run = (
    await client.query<{ id: string }>("SELECT id FROM agent_runs LIMIT 1")
  ).rows[0]!.id;
  await assert.rejects(
    client.query("UPDATE agent_runs SET launch_snapshot = $1 WHERE id = $2", [
      JSON.stringify({ schemaVersion: 4, framework: "pi" }),
      run,
    ]),
    /agent_runs_launch_snapshot_check/,
  );
  await client.query("BEGIN");
  await client.query(
    "UPDATE agent_runs SET launch_snapshot = $1 WHERE id = $2",
    [
      JSON.stringify({
        schemaVersion: 4,
        framework: "pi",
        executionMode: "api-inference",
        inferenceContractVersion: 1,
      }),
      run,
    ],
  );
  await client.query("ROLLBACK");
  await client.query(
    "ALTER TABLE drizzle.__drizzle_migrations DROP CONSTRAINT foundation_inject_failure",
  );
  await apply();
  assert.equal(await constraint(), true);
  console.log(
    "PASS validation failure preserves committed additive frontier; retry validates unchanged historical records",
  );

  await client.query("BEGIN");
  try {
    await client.query(`INSERT INTO agent_run_inference
      (run_id, input, phase, owner_epoch, deadline_at, provider_attempt_id, provider_attempt_state)
      SELECT id, '{"schemaVersion":1,"inputEventId":null,"inputGeneration":0,"configurationHash":"${"a".repeat(64)}","contextHash":"${"b".repeat(64)}","h0":{"kind":"empty"},"deferredSecrets":{"kind":"none"}}',
        'terminal', 1, now() + row_number() OVER () * interval '1 second', gen_random_uuid(), 'not-started'
      FROM agent_runs LIMIT 10000;
      INSERT INTO agent_run_sandbox_intent (run_id, generation, continuation, state, enqueued_at, expires_at, owner_epoch)
      SELECT run_id, 1, '{"mode":"untouched-h0"}', 'waiting', deadline_at, deadline_at + interval '2 hours', 1 FROM agent_run_inference;
      INSERT INTO agent_run_sandbox_lease (run_id, state, owner_epoch, deadline_at, release_evidence)
      SELECT run_id, 'released', 1, expires_at, 'fixture:never-started' FROM agent_run_sandbox_intent;
      ANALYZE agent_run_inference; ANALYZE agent_run_sandbox_intent; ANALYZE agent_run_sandbox_lease;`);
    for (const [table, stateColumn, state, timeColumn, index] of [
      [
        "agent_run_inference",
        "phase",
        "terminal",
        "deadline_at",
        "agent_run_inference_deadline_idx",
      ],
      [
        "agent_run_sandbox_intent",
        "state",
        "waiting",
        "enqueued_at",
        "agent_run_sandbox_intent_queue_idx",
      ],
      [
        "agent_run_sandbox_intent",
        "state",
        "waiting",
        "expires_at",
        "agent_run_sandbox_intent_expiry_idx",
      ],
      [
        "agent_run_sandbox_lease",
        "state",
        "released",
        "deadline_at",
        "agent_run_sandbox_lease_deadline_idx",
      ],
    ]) {
      const plan = (
        await client.query(
          `EXPLAIN (ANALYZE, FORMAT JSON) SELECT run_id FROM ${table} WHERE ${stateColumn} = '${state}' ORDER BY ${timeColumn}, run_id LIMIT 1`,
        )
      ).rows;
      assert.ok(
        JSON.stringify(plan).includes(index!),
        `Expected ordered bounded scan on ${index}`,
      );
      console.log(`PASS indexed bounded deadline/claim plan: ${index}`);
    }
    // Parent deletion cannot manufacture proof that a reservation was released.
    await assert.rejects(
      client.query(
        "DELETE FROM agent_runs WHERE id = (SELECT run_id FROM agent_run_sandbox_lease LIMIT 1)",
      ),
      /foreign key constraint/,
    );
  } finally {
    await client.query("ROLLBACK");
  }
  console.log("PASS lease FK blocks implicit capacity erasure");
} finally {
  await client.end();
  await admin.query(`DROP DATABASE IF EXISTS "${database}" WITH (FORCE)`);
  await admin.end();
  await rm(fixture, { recursive: true, force: true });
}
