// Test-process-only values. Never load production configuration for synthetic
// dual-store acceptance. DATABASE_URL is separately restricted to a local host.
Object.assign(process.env, {
  CLERK_SECRET_KEY: "sk_test_synthetic",
  CLERK_PUBLISHABLE_KEY: "pk_test_synthetic",
  SECRETS_ENCRYPTION_KEY: "0".repeat(64),
  OFFICIAL_RUNNER_SECRET: "1".repeat(64),
  OPENAI_API_KEY: "synthetic",
  GIT_COMMIT_SHA: "synthetic",
  ENV: "development",
  FEISHU_CALLBACK_BASE_URL: "https://synthetic.invalid",
  OKOU_WEB_URL: "https://synthetic.invalid",
  APP_URL: "https://synthetic.invalid",
  CLI_PKG_URL: "https://synthetic.invalid/package.tgz",
  CRON_SECRET: "synthetic",
  R2_ACCESS_KEY_ID: "synthetic",
  R2_ACCOUNT_ID: "synthetic",
  R2_SECRET_ACCESS_KEY: "synthetic",
  R2_USER_STORAGES_BUCKET_NAME: "synthetic",
  R2_USER_ARTIFACTS_BUCKET_NAME: "synthetic",
  R2_USER_ARTIFACTS_ACCESS_KEY_ID: "synthetic",
  R2_USER_ARTIFACTS_SECRET_ACCESS_KEY: "synthetic",
  PUBLIC_ARTIFACTS_BASE_URL: "https://synthetic.invalid",
  OKOU_PUBLIC_ARTIFACTS_BASE_URL: "https://synthetic.invalid",
  OKOU_PUBLIC_HOST_DOMAIN: "synthetic.invalid",
  OKOU_HOST_SCHEME: "https",
  AXIOM_TOKEN_SESSIONS: "synthetic",
  AXIOM_TOKEN_TELEMETRY: "synthetic",
  AXIOM_DATASET_SUFFIX: "dev",
  STRIPE_SECRET_KEY: "synthetic",
  ABLY_API_KEY: "synthetic",
});
