import sessionConstruction from "../session-construction-digest.json";

/**
 * Build-time digest of the code-determined Pi session construction: the
 * system prompt template and the ordered tool schemas the runtime produces
 * for fixed synthetic inputs, hashed over a fixed set of profiles.
 *
 * The API records it in every Pi launch config and the sandbox compares it
 * before continuing an API-first pending-tool handoff, because prompt and
 * tool-schema parity between the two owners is a byte-equality contract.
 * Unlike `PI_AGENT_RUNTIME_VERSION` it moves only when code that feeds the
 * constructed session changes, in whichever package that code lives, so a
 * dependency-only release bump keeps the rootfs-installed CLI usable.
 *
 * `session-construction-digest.json` is regenerated by
 * `pnpm --filter @okouai/pi-agent-runtime update-session-construction-digest`;
 * `session-construction-digest.test.ts` fails while it is stale.
 */
export const PI_SESSION_CONSTRUCTION_DIGEST: string =
  sessionConstruction.digest;
