import sessionConstruction from "../session-construction-digest.json";

/**
 * Build-time digest of the code-determined Pi session construction: the
 * system prompt template and the ordered tool schemas the runtime produces
 * for fixed synthetic inputs, plus verified model-limit corrections.
 *
 * The API records it in every Pi launch config and the sandbox compares it
 * before starting a session, so installed and captured builds agree on
 * the code-defined prompt and tool schemas.
 * Unlike `PI_AGENT_RUNTIME_VERSION` it moves only when code that feeds the
 * constructed session or its verified model limits changes, in whichever
 * package that code lives, so a version-only release bump keeps the
 * rootfs-installed CLI usable.
 *
 * `session-construction-digest.json` is regenerated by
 * `pnpm --filter @okouai/pi-agent-runtime update-session-construction-digest`;
 * `session-construction-digest.test.ts` fails while it is stale.
 */
export const PI_SESSION_CONSTRUCTION_DIGEST: string =
  sessionConstruction.digest;
