const testApiCommit = "a".repeat(40);

export const apiTestEnvironment = {
  TZ: "UTC",
  CLERK_SECRET_KEY: "sk_test_dummy_for_unit_tests",
  CLERK_PUBLISHABLE_KEY: "pk_test_dummy_for_unit_tests",
  SECRETS_ENCRYPTION_KEY:
    "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
  OFFICIAL_RUNNER_SECRET:
    "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
  OPENAI_API_KEY: "test-openai-key",
  FAL_KEY: "test-fal-key",
  CRON_SECRET: "test-cron-secret",
  R2_ACCESS_KEY_ID: "test-access-key",
  R2_ACCOUNT_ID: "test-account",
  R2_SECRET_ACCESS_KEY: "test-secret-key",
  R2_USER_STORAGES_BUCKET_NAME: "test-user-storages",
  R2_PRIVATE_ARTIFACTS_BUCKET_NAME: "test-private-artifacts",
  R2_PRIVATE_ARTIFACTS_ACCESS_KEY_ID: "test-private-access-key",
  R2_PRIVATE_ARTIFACTS_SECRET_ACCESS_KEY: "test-private-secret-key",
  R2_USER_ARTIFACTS_BUCKET_NAME: "test-user-artifacts",
  R2_USER_ARTIFACTS_ACCESS_KEY_ID: "test-artifacts-access-key",
  R2_USER_ARTIFACTS_SECRET_ACCESS_KEY: "test-artifacts-secret-key",
  PUBLIC_ARTIFACTS_BASE_URL: "https://cdn.vm7.io",
  OKOU_PUBLIC_ARTIFACTS_BASE_URL: "https://a.okou.io",
  PUBLIC_ARTIFACT_SHARES_BASE_URL: "https://a.okou.io",
  R2_HOSTED_SITES_BUCKET_NAME: "test-hosted-sites",
  R2_HOSTED_SITES_ACCESS_KEY_ID: "test-hosted-sites-access-key",
  R2_HOSTED_SITES_SECRET_ACCESS_KEY: "test-hosted-sites-secret-key",
  OKOU_PUBLIC_HOST_DOMAIN: "okou.app",
  OKOU_HOST_SCHEME: "https",
  ZERO_HOST_DOMAIN: "sites.example.com",
  ZERO_HOST_SCHEME: "https",
  OKOU_API_BACKEND_URL: "http://localhost:3000",
  FEISHU_CALLBACK_BASE_URL: "http://localhost:3000",
  OKOU_WEB_URL: "http://localhost:3001",
  APP_URL: "http://localhost:3002",
  CLI_PKG_URL: `https://static.okou.io/okou-cli/${testApiCommit}/package.tgz`,
  RESEND_API_KEY: "test-resend-key",
  RESEND_WEBHOOK_SECRET: "whsec_test",
  RESEND_FROM_DOMAIN: "mail.example.com",
  GIT_COMMIT_SHA: testApiCommit,
  ENV: "development",
  AXIOM_TOKEN_SESSIONS: "xaat-test-sessions",
  AXIOM_TOKEN_TELEMETRY: "xaat-test-telemetry",
  AXIOM_DATASET_SUFFIX: "dev",
  STRIPE_SECRET_KEY: "sk_test_dummy_for_unit_tests",
  ATOM_URL: "https://atom.example.test",
  OKOU_MACHINE_SECRET_KEY: "msk_test_dummy_for_unit_tests",
  ABLY_API_KEY: "test-ably-key",
  VERCEL_INTEGRATION_SLUG: "okou-test-integration",
  VITEST: "true",
} as const;
