import type { PiCatalogSource } from "../pi-execution";

/**
 * Active rows of `run_model_catalog` and the Built-in and personal subscription
 * `model_routes` rows seeded by migrations 1298 and 1301, so admission tests
 * read the same catalog data the API serves.
 */
export const SEEDED_MODEL_CATALOG: PiCatalogSource = {
  models: [
    { model: "okou-1.0", piRouteClass: "gpt-codex" },
    { model: "claude-fable-5-1", piRouteClass: null },
    { model: "claude-opus-5-5", piRouteClass: "claude-native" },
    { model: "claude-opus-5", piRouteClass: "claude-native" },
    { model: "claude-sonnet-5-5", piRouteClass: "claude-native" },
    { model: "claude-sonnet-5", piRouteClass: "claude-native" },
    { model: "gpt-6-astra", piRouteClass: null },
    { model: "gpt-6.1-sol", piRouteClass: "gpt-codex" },
    { model: "gpt-6-sol", piRouteClass: "gpt-codex" },
    { model: "gpt-6-luna", piRouteClass: "gpt-codex" },
    { model: "gpt-5.6-sol", piRouteClass: "gpt-codex" },
    { model: "gpt-5.6-luna", piRouteClass: "gpt-codex" },
    { model: "deepseek-v4.1-flash", piRouteClass: "deepseek" },
    { model: "deepseek-v4-flash", piRouteClass: "deepseek" },
  ],
  routes: [
    {
      model: "claude-fable-5-1",
      providerType: "built-in",
      concreteProviderType: "anthropic-api-key",
      subscriptionType: null,
      upstreamModel: "claude-fable-5-1",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "claude-fable-5-1",
      providerType: "built-in",
      concreteProviderType: "openrouter-api-key",
      subscriptionType: null,
      upstreamModel: "anthropic/claude-fable-5.1",
      enabled: true,
      priority: 1,
      serviceTiers: [],
    },
    {
      model: "claude-fable-5-1",
      providerType: "claude-code-oauth-token",
      concreteProviderType: "claude-code-oauth-token",
      subscriptionType: null,
      upstreamModel: "claude-fable-5-1",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "claude-fable-5-1",
      providerType: "claude-code-oauth-token",
      concreteProviderType: "claude-code-oauth-token",
      subscriptionType: "claude-code-oauth-token",
      upstreamModel: "claude-fable-5-1",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "claude-opus-5",
      providerType: "built-in",
      concreteProviderType: "anthropic-api-key",
      subscriptionType: null,
      upstreamModel: "claude-opus-5",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "claude-opus-5",
      providerType: "built-in",
      concreteProviderType: "openrouter-api-key",
      subscriptionType: null,
      upstreamModel: "anthropic/claude-opus-5",
      enabled: true,
      priority: 1,
      serviceTiers: [],
    },
    {
      model: "claude-opus-5",
      providerType: "claude-code-oauth-token",
      concreteProviderType: "claude-code-oauth-token",
      subscriptionType: null,
      upstreamModel: "claude-opus-5",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "claude-opus-5-5",
      providerType: "built-in",
      concreteProviderType: "anthropic-api-key",
      subscriptionType: null,
      upstreamModel: "claude-opus-5-5",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "claude-opus-5-5",
      providerType: "built-in",
      concreteProviderType: "openrouter-api-key",
      subscriptionType: null,
      upstreamModel: "anthropic/claude-opus-5.5",
      enabled: true,
      priority: 1,
      serviceTiers: [],
    },
    {
      model: "claude-opus-5-5",
      providerType: "claude-code-oauth-token",
      concreteProviderType: "claude-code-oauth-token",
      subscriptionType: null,
      upstreamModel: "claude-opus-5-5",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "claude-opus-5-5",
      providerType: "claude-code-oauth-token",
      concreteProviderType: "claude-code-oauth-token",
      subscriptionType: "claude-code-oauth-token",
      upstreamModel: "claude-opus-5-5",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "claude-sonnet-5",
      providerType: "built-in",
      concreteProviderType: "anthropic-api-key",
      subscriptionType: null,
      upstreamModel: "claude-sonnet-5",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "claude-sonnet-5",
      providerType: "built-in",
      concreteProviderType: "openrouter-api-key",
      subscriptionType: null,
      upstreamModel: "anthropic/claude-sonnet-5",
      enabled: true,
      priority: 1,
      serviceTiers: [],
    },
    {
      model: "claude-sonnet-5",
      providerType: "claude-code-oauth-token",
      concreteProviderType: "claude-code-oauth-token",
      subscriptionType: null,
      upstreamModel: "claude-sonnet-5",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "claude-sonnet-5-5",
      providerType: "built-in",
      concreteProviderType: "anthropic-api-key",
      subscriptionType: null,
      upstreamModel: "claude-sonnet-5-5",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "claude-sonnet-5-5",
      providerType: "claude-code-oauth-token",
      concreteProviderType: "claude-code-oauth-token",
      subscriptionType: null,
      upstreamModel: "claude-sonnet-5-5",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "claude-sonnet-5-5",
      providerType: "claude-code-oauth-token",
      concreteProviderType: "claude-code-oauth-token",
      subscriptionType: "claude-code-oauth-token",
      upstreamModel: "claude-sonnet-5-5",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "deepseek-v4-flash",
      providerType: "built-in",
      concreteProviderType: "deepseek",
      subscriptionType: null,
      upstreamModel: "deepseek-v4-flash",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "deepseek-v4-flash",
      providerType: "built-in",
      concreteProviderType: "openrouter-codex",
      subscriptionType: null,
      upstreamModel: "deepseek/deepseek-v4-flash",
      enabled: true,
      priority: 1,
      serviceTiers: [],
    },
    {
      model: "deepseek-v4.1-flash",
      providerType: "built-in",
      concreteProviderType: "deepseek",
      subscriptionType: null,
      upstreamModel: "deepseek-flash",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
    {
      model: "deepseek-v4.1-flash",
      providerType: "built-in",
      concreteProviderType: "openrouter-codex",
      subscriptionType: null,
      upstreamModel: "deepseek/deepseek-v4.1-flash",
      enabled: true,
      priority: 1,
      serviceTiers: [],
    },
    {
      model: "gpt-5.6-luna",
      providerType: "built-in",
      concreteProviderType: "openai-api-key",
      subscriptionType: null,
      upstreamModel: "gpt-5.6-luna",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-5.6-luna",
      providerType: "built-in",
      concreteProviderType: "openrouter-codex",
      subscriptionType: null,
      upstreamModel: "openai/gpt-5.6-luna",
      enabled: true,
      priority: 1,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-5.6-luna",
      providerType: "codex-oauth-token",
      concreteProviderType: "codex-oauth-token",
      subscriptionType: null,
      upstreamModel: "gpt-5.6-luna",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-5.6-sol",
      providerType: "built-in",
      concreteProviderType: "openai-api-key",
      subscriptionType: null,
      upstreamModel: "gpt-5.6-sol",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-5.6-sol",
      providerType: "built-in",
      concreteProviderType: "openrouter-codex",
      subscriptionType: null,
      upstreamModel: "openai/gpt-5.6-sol",
      enabled: true,
      priority: 1,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-5.6-sol",
      providerType: "codex-oauth-token",
      concreteProviderType: "codex-oauth-token",
      subscriptionType: null,
      upstreamModel: "gpt-5.6-sol",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6-astra",
      providerType: "built-in",
      concreteProviderType: "openai-api-key",
      subscriptionType: null,
      upstreamModel: "gpt-6-astra",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6-astra",
      providerType: "built-in",
      concreteProviderType: "openrouter-codex",
      subscriptionType: null,
      upstreamModel: "openai/gpt-6-astra",
      enabled: true,
      priority: 1,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6-astra",
      providerType: "codex-oauth-token",
      concreteProviderType: "codex-oauth-token",
      subscriptionType: null,
      upstreamModel: "gpt-6-astra",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6-astra",
      providerType: "codex-oauth-token",
      concreteProviderType: "codex-oauth-token",
      subscriptionType: "codex-oauth-token",
      upstreamModel: "gpt-6-astra",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6-luna",
      providerType: "built-in",
      concreteProviderType: "openai-api-key",
      subscriptionType: null,
      upstreamModel: "gpt-6-luna",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6-luna",
      providerType: "built-in",
      concreteProviderType: "openrouter-codex",
      subscriptionType: null,
      upstreamModel: "openai/gpt-6-luna",
      enabled: true,
      priority: 1,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6-luna",
      providerType: "codex-oauth-token",
      concreteProviderType: "codex-oauth-token",
      subscriptionType: null,
      upstreamModel: "gpt-6-luna",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6-luna",
      providerType: "codex-oauth-token",
      concreteProviderType: "codex-oauth-token",
      subscriptionType: "codex-oauth-token",
      upstreamModel: "gpt-6-luna",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6-sol",
      providerType: "built-in",
      concreteProviderType: "openai-api-key",
      subscriptionType: null,
      upstreamModel: "gpt-6-sol",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6-sol",
      providerType: "built-in",
      concreteProviderType: "openrouter-codex",
      subscriptionType: null,
      upstreamModel: "openai/gpt-6-sol",
      enabled: true,
      priority: 1,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6-sol",
      providerType: "codex-oauth-token",
      concreteProviderType: "codex-oauth-token",
      subscriptionType: null,
      upstreamModel: "gpt-6-sol",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6-sol",
      providerType: "codex-oauth-token",
      concreteProviderType: "codex-oauth-token",
      subscriptionType: "codex-oauth-token",
      upstreamModel: "gpt-6-sol",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6.1-sol",
      providerType: "built-in",
      concreteProviderType: "openai-api-key",
      subscriptionType: null,
      upstreamModel: "gpt-6.1-sol",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6.1-sol",
      providerType: "codex-oauth-token",
      concreteProviderType: "codex-oauth-token",
      subscriptionType: null,
      upstreamModel: "gpt-6.1-sol",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "gpt-6.1-sol",
      providerType: "codex-oauth-token",
      concreteProviderType: "codex-oauth-token",
      subscriptionType: "codex-oauth-token",
      upstreamModel: "gpt-6.1-sol",
      enabled: true,
      priority: 0,
      serviceTiers: ["priority"],
    },
    {
      model: "okou-1.0",
      providerType: "built-in",
      concreteProviderType: "openrouter-codex",
      subscriptionType: null,
      upstreamModel: "@preset/okou-1-0",
      enabled: true,
      priority: 0,
      serviceTiers: [],
    },
  ],
};

/** Distinct provider types of a model's enabled seeded routes. */
export function seededProviderTypes(model: string): readonly string[] {
  return [
    ...new Set(
      SEEDED_MODEL_CATALOG.routes
        .filter((route) => {
          return route.enabled && route.model === model;
        })
        .map((route) => {
          return route.providerType;
        }),
    ),
  ];
}

/** Seeded catalog models with at least one enabled route, in catalog order. */
export const SEEDED_ROUTED_MODELS: readonly string[] =
  SEEDED_MODEL_CATALOG.models
    .map((entry) => {
      return entry.model;
    })
    .filter((model) => {
      return seededProviderTypes(model).length > 0;
    });
