ALTER TABLE "vnc_connections" DROP CONSTRAINT "chk_vnc_connections_profile";--> statement-breakpoint
ALTER TABLE "vnc_credentials" DROP CONSTRAINT "chk_vnc_credentials_auth";--> statement-breakpoint
ALTER TABLE "vnc_credentials" DROP CONSTRAINT "chk_vnc_credentials_password";--> statement-breakpoint
ALTER TABLE "vnc_connections" ADD COLUMN "kerberos_service" jsonb;--> statement-breakpoint
ALTER TABLE "vnc_connections" ADD COLUMN "kdc_transport_type" varchar(16);--> statement-breakpoint
ALTER TABLE "vnc_connections" ADD COLUMN "kdc_host" varchar(253);--> statement-breakpoint
ALTER TABLE "vnc_connections" ADD COLUMN "kdc_port" integer;--> statement-breakpoint
ALTER TABLE "vnc_connections" ADD COLUMN "kdc_ssh_connection_id" uuid;--> statement-breakpoint
ALTER TABLE "vnc_connections" ADD COLUMN "kerberos_ticket_lifetime_seconds" integer;--> statement-breakpoint
ALTER TABLE "vnc_connections" ADD COLUMN "kerberos_renewable_lifetime_seconds" integer;--> statement-breakpoint
ALTER TABLE "vnc_credentials" ADD COLUMN "encrypted_kerberos_credential" text;--> statement-breakpoint
ALTER TABLE "vnc_credentials" ADD COLUMN "kerberos_initiator" jsonb;--> statement-breakpoint
ALTER TABLE "vnc_credentials" ADD COLUMN "kerberos_service" jsonb;--> statement-breakpoint
ALTER TABLE "vnc_credentials" ADD COLUMN "kerberos_declared_expires_at" bigint;--> statement-breakpoint
ALTER TABLE "vnc_connections" ADD CONSTRAINT "vnc_connections_kdc_ssh_owner_fk" FOREIGN KEY ("kdc_ssh_connection_id","org_id","user_id") REFERENCES "public"."ssh_connections"("id","org_id","user_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vnc_connections" ADD CONSTRAINT "chk_vnc_connections_kerberos_service" CHECK (CASE WHEN "vnc_connections"."kerberos_service" IS NULL THEN true
    WHEN jsonb_typeof("vnc_connections"."kerberos_service") = 'object'
      AND jsonb_typeof("vnc_connections"."kerberos_service"->'realm') = 'string'
      AND jsonb_typeof("vnc_connections"."kerberos_service"->'components') = 'array'
    THEN ("vnc_connections"."kerberos_service" - 'realm' - 'components' = '{}'::jsonb
      AND jsonb_array_length("vnc_connections"."kerberos_service"->'components') BETWEEN 1 AND 8
      AND NOT jsonb_path_exists("vnc_connections"."kerberos_service", '$.components[*] ? (@.type() != "string" || @ == "")')
      AND ("vnc_connections"."kerberos_service"->>'realm' IS NULL OR (octet_length("vnc_connections"."kerberos_service"->>'realm') BETWEEN 1 AND 255 AND "vnc_connections"."kerberos_service"->>'realm' !~ '[[:cntrl:]]')) AND ("vnc_connections"."kerberos_service"->'components'->>0 IS NULL OR (octet_length("vnc_connections"."kerberos_service"->'components'->>0) BETWEEN 1 AND 255 AND "vnc_connections"."kerberos_service"->'components'->>0 !~ '[[:cntrl:]]')) AND ("vnc_connections"."kerberos_service"->'components'->>1 IS NULL OR (octet_length("vnc_connections"."kerberos_service"->'components'->>1) BETWEEN 1 AND 255 AND "vnc_connections"."kerberos_service"->'components'->>1 !~ '[[:cntrl:]]')) AND ("vnc_connections"."kerberos_service"->'components'->>2 IS NULL OR (octet_length("vnc_connections"."kerberos_service"->'components'->>2) BETWEEN 1 AND 255 AND "vnc_connections"."kerberos_service"->'components'->>2 !~ '[[:cntrl:]]')) AND ("vnc_connections"."kerberos_service"->'components'->>3 IS NULL OR (octet_length("vnc_connections"."kerberos_service"->'components'->>3) BETWEEN 1 AND 255 AND "vnc_connections"."kerberos_service"->'components'->>3 !~ '[[:cntrl:]]')) AND ("vnc_connections"."kerberos_service"->'components'->>4 IS NULL OR (octet_length("vnc_connections"."kerberos_service"->'components'->>4) BETWEEN 1 AND 255 AND "vnc_connections"."kerberos_service"->'components'->>4 !~ '[[:cntrl:]]')) AND ("vnc_connections"."kerberos_service"->'components'->>5 IS NULL OR (octet_length("vnc_connections"."kerberos_service"->'components'->>5) BETWEEN 1 AND 255 AND "vnc_connections"."kerberos_service"->'components'->>5 !~ '[[:cntrl:]]')) AND ("vnc_connections"."kerberos_service"->'components'->>6 IS NULL OR (octet_length("vnc_connections"."kerberos_service"->'components'->>6) BETWEEN 1 AND 255 AND "vnc_connections"."kerberos_service"->'components'->>6 !~ '[[:cntrl:]]')) AND ("vnc_connections"."kerberos_service"->'components'->>7 IS NULL OR (octet_length("vnc_connections"."kerberos_service"->'components'->>7) BETWEEN 1 AND 255 AND "vnc_connections"."kerberos_service"->'components'->>7 !~ '[[:cntrl:]]')) AND (coalesce(octet_length("vnc_connections"."kerberos_service"->>'realm'), 0) + coalesce(octet_length("vnc_connections"."kerberos_service"->'components'->>0), 0) + coalesce(octet_length("vnc_connections"."kerberos_service"->'components'->>1), 0) + coalesce(octet_length("vnc_connections"."kerberos_service"->'components'->>2), 0) + coalesce(octet_length("vnc_connections"."kerberos_service"->'components'->>3), 0) + coalesce(octet_length("vnc_connections"."kerberos_service"->'components'->>4), 0) + coalesce(octet_length("vnc_connections"."kerberos_service"->'components'->>5), 0) + coalesce(octet_length("vnc_connections"."kerberos_service"->'components'->>6), 0) + coalesce(octet_length("vnc_connections"."kerberos_service"->'components'->>7), 0)) <= 1024
      AND jsonb_array_length("vnc_connections"."kerberos_service"->'components') = 2 AND "vnc_connections"."kerberos_service"->'components'->>0 = 'vnc')
    ELSE false END);--> statement-breakpoint
ALTER TABLE "vnc_connections" ADD CONSTRAINT "chk_vnc_connections_kerberos" CHECK (CASE
        WHEN "vnc_connections"."auth_method" IN ('qemu_kerberos_ticket', 'qemu_kerberos_keytab', 'qemu_kerberos_password')
          THEN "vnc_connections"."kerberos_service" IS NOT NULL AND "vnc_connections"."security_type" = 'qemu_x509_gssapi'
        ELSE "vnc_connections"."kerberos_service" IS NULL END);--> statement-breakpoint
ALTER TABLE "vnc_connections" ADD CONSTRAINT "chk_vnc_connections_kdc" CHECK (CASE
        WHEN "vnc_connections"."auth_method" IN ('qemu_kerberos_keytab', 'qemu_kerberos_password') THEN
          "vnc_connections"."kdc_transport_type" IS NOT NULL AND "vnc_connections"."kdc_host" IS NOT NULL
          AND octet_length("vnc_connections"."kdc_host") BETWEEN 1 AND 253
          AND "vnc_connections"."kdc_port" IS NOT NULL AND "vnc_connections"."kdc_port" BETWEEN 1 AND 65535
          AND "vnc_connections"."kerberos_ticket_lifetime_seconds" IS NOT NULL AND "vnc_connections"."kerberos_ticket_lifetime_seconds" BETWEEN 1 AND 7200
          AND "vnc_connections"."kerberos_renewable_lifetime_seconds" IS NOT NULL AND "vnc_connections"."kerberos_renewable_lifetime_seconds" BETWEEN 0 AND 7200
          AND (("vnc_connections"."kdc_transport_type" = 'direct' AND "vnc_connections"."kdc_ssh_connection_id" IS NULL)
            OR ("vnc_connections"."kdc_transport_type" = 'ssh' AND "vnc_connections"."kdc_ssh_connection_id" IS NOT NULL AND "vnc_connections"."kdc_host" IN ('127.0.0.1', '::1')))
        ELSE "vnc_connections"."kdc_transport_type" IS NULL AND "vnc_connections"."kdc_host" IS NULL AND "vnc_connections"."kdc_port" IS NULL
          AND "vnc_connections"."kdc_ssh_connection_id" IS NULL AND "vnc_connections"."kerberos_ticket_lifetime_seconds" IS NULL
          AND "vnc_connections"."kerberos_renewable_lifetime_seconds" IS NULL END);--> statement-breakpoint
ALTER TABLE "vnc_connections" ADD CONSTRAINT "chk_vnc_connections_profile" CHECK (("vnc_connections"."credential_id" IS NOT NULL AND "vnc_connections"."auth_method" IN ('rsa_aes_password', 'rsa_aes_username_password') AND (("vnc_connections"."security_type" IN ('rsa_aes_ra2', 'rsa_aes_ra2_256')) OR ("vnc_connections"."security_type" IN ('rsa_aes_ra2ne', 'rsa_aes_ra2ne_256') AND "vnc_connections"."transport_type" = 'ssh' AND "vnc_connections"."host" IN ('127.0.0.1', '::1')))) OR ("vnc_connections"."auth_method" = 'none' AND "vnc_connections"."security_type" = 'x509_none' AND "vnc_connections"."credential_id" IS NULL) OR ("vnc_connections"."credential_id" IS NOT NULL AND (("vnc_connections"."auth_method" = 'client_certificate' AND "vnc_connections"."security_type" = 'x509_none') OR ("vnc_connections"."auth_method" = 'client_certificate_vnc_password' AND "vnc_connections"."security_type" = 'x509_vnc') OR ("vnc_connections"."auth_method" = 'vnc_password' AND "vnc_connections"."security_type" = 'x509_vnc') OR ("vnc_connections"."auth_method" = 'vnc_password' AND "vnc_connections"."security_type" = 'apple_vnc_password' AND "vnc_connections"."transport_type" = 'ssh' AND "vnc_connections"."host" IN ('127.0.0.1', '::1') AND "vnc_connections"."x509_server_name" IS NULL) OR ("vnc_connections"."auth_method" = 'username_password' AND "vnc_connections"."security_type" = 'x509_plain') OR ("vnc_connections"."auth_method" = 'qemu_scram_sha256' AND "vnc_connections"."security_type" = 'qemu_x509_sasl') OR ("vnc_connections"."auth_method" = 'apple_dh_username_password' AND "vnc_connections"."security_type" = 'apple_dh' AND "vnc_connections"."transport_type" = 'ssh' AND "vnc_connections"."host" IN ('127.0.0.1', '::1') AND "vnc_connections"."x509_server_name" IS NULL) OR ("vnc_connections"."auth_method" = 'apple_srp_username_password' AND "vnc_connections"."security_type" = 'apple_srp' AND "vnc_connections"."transport_type" = 'ssh' AND "vnc_connections"."host" IN ('127.0.0.1', '::1') AND "vnc_connections"."x509_server_name" IS NULL) OR ("vnc_connections"."auth_method" = 'apple_rsa_srp_username_password' AND "vnc_connections"."security_type" = 'apple_rsa_srp' AND "vnc_connections"."transport_type" = 'ssh' AND "vnc_connections"."host" IN ('127.0.0.1', '::1') AND "vnc_connections"."x509_server_name" IS NULL))) OR ("vnc_connections"."auth_method" IN ('qemu_kerberos_ticket', 'qemu_kerberos_keytab', 'qemu_kerberos_password') AND "vnc_connections"."security_type" = 'qemu_x509_gssapi' AND "vnc_connections"."credential_id" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "vnc_credentials" ADD CONSTRAINT "chk_vnc_credentials_kerberos_initiator" CHECK (CASE WHEN "vnc_credentials"."kerberos_initiator" IS NULL THEN true
    WHEN jsonb_typeof("vnc_credentials"."kerberos_initiator") = 'object'
      AND jsonb_typeof("vnc_credentials"."kerberos_initiator"->'realm') = 'string'
      AND jsonb_typeof("vnc_credentials"."kerberos_initiator"->'components') = 'array'
    THEN ("vnc_credentials"."kerberos_initiator" - 'realm' - 'components' = '{}'::jsonb
      AND jsonb_array_length("vnc_credentials"."kerberos_initiator"->'components') BETWEEN 1 AND 8
      AND NOT jsonb_path_exists("vnc_credentials"."kerberos_initiator", '$.components[*] ? (@.type() != "string" || @ == "")')
      AND ("vnc_credentials"."kerberos_initiator"->>'realm' IS NULL OR (octet_length("vnc_credentials"."kerberos_initiator"->>'realm') BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_initiator"->>'realm' !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_initiator"->'components'->>0 IS NULL OR (octet_length("vnc_credentials"."kerberos_initiator"->'components'->>0) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_initiator"->'components'->>0 !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_initiator"->'components'->>1 IS NULL OR (octet_length("vnc_credentials"."kerberos_initiator"->'components'->>1) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_initiator"->'components'->>1 !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_initiator"->'components'->>2 IS NULL OR (octet_length("vnc_credentials"."kerberos_initiator"->'components'->>2) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_initiator"->'components'->>2 !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_initiator"->'components'->>3 IS NULL OR (octet_length("vnc_credentials"."kerberos_initiator"->'components'->>3) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_initiator"->'components'->>3 !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_initiator"->'components'->>4 IS NULL OR (octet_length("vnc_credentials"."kerberos_initiator"->'components'->>4) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_initiator"->'components'->>4 !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_initiator"->'components'->>5 IS NULL OR (octet_length("vnc_credentials"."kerberos_initiator"->'components'->>5) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_initiator"->'components'->>5 !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_initiator"->'components'->>6 IS NULL OR (octet_length("vnc_credentials"."kerberos_initiator"->'components'->>6) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_initiator"->'components'->>6 !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_initiator"->'components'->>7 IS NULL OR (octet_length("vnc_credentials"."kerberos_initiator"->'components'->>7) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_initiator"->'components'->>7 !~ '[[:cntrl:]]')) AND (coalesce(octet_length("vnc_credentials"."kerberos_initiator"->>'realm'), 0) + coalesce(octet_length("vnc_credentials"."kerberos_initiator"->'components'->>0), 0) + coalesce(octet_length("vnc_credentials"."kerberos_initiator"->'components'->>1), 0) + coalesce(octet_length("vnc_credentials"."kerberos_initiator"->'components'->>2), 0) + coalesce(octet_length("vnc_credentials"."kerberos_initiator"->'components'->>3), 0) + coalesce(octet_length("vnc_credentials"."kerberos_initiator"->'components'->>4), 0) + coalesce(octet_length("vnc_credentials"."kerberos_initiator"->'components'->>5), 0) + coalesce(octet_length("vnc_credentials"."kerberos_initiator"->'components'->>6), 0) + coalesce(octet_length("vnc_credentials"."kerberos_initiator"->'components'->>7), 0)) <= 1024
      )
    ELSE false END);--> statement-breakpoint
ALTER TABLE "vnc_credentials" ADD CONSTRAINT "chk_vnc_credentials_kerberos_service" CHECK (CASE WHEN "vnc_credentials"."kerberos_service" IS NULL THEN true
    WHEN jsonb_typeof("vnc_credentials"."kerberos_service") = 'object'
      AND jsonb_typeof("vnc_credentials"."kerberos_service"->'realm') = 'string'
      AND jsonb_typeof("vnc_credentials"."kerberos_service"->'components') = 'array'
    THEN ("vnc_credentials"."kerberos_service" - 'realm' - 'components' = '{}'::jsonb
      AND jsonb_array_length("vnc_credentials"."kerberos_service"->'components') BETWEEN 1 AND 8
      AND NOT jsonb_path_exists("vnc_credentials"."kerberos_service", '$.components[*] ? (@.type() != "string" || @ == "")')
      AND ("vnc_credentials"."kerberos_service"->>'realm' IS NULL OR (octet_length("vnc_credentials"."kerberos_service"->>'realm') BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_service"->>'realm' !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_service"->'components'->>0 IS NULL OR (octet_length("vnc_credentials"."kerberos_service"->'components'->>0) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_service"->'components'->>0 !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_service"->'components'->>1 IS NULL OR (octet_length("vnc_credentials"."kerberos_service"->'components'->>1) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_service"->'components'->>1 !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_service"->'components'->>2 IS NULL OR (octet_length("vnc_credentials"."kerberos_service"->'components'->>2) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_service"->'components'->>2 !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_service"->'components'->>3 IS NULL OR (octet_length("vnc_credentials"."kerberos_service"->'components'->>3) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_service"->'components'->>3 !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_service"->'components'->>4 IS NULL OR (octet_length("vnc_credentials"."kerberos_service"->'components'->>4) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_service"->'components'->>4 !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_service"->'components'->>5 IS NULL OR (octet_length("vnc_credentials"."kerberos_service"->'components'->>5) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_service"->'components'->>5 !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_service"->'components'->>6 IS NULL OR (octet_length("vnc_credentials"."kerberos_service"->'components'->>6) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_service"->'components'->>6 !~ '[[:cntrl:]]')) AND ("vnc_credentials"."kerberos_service"->'components'->>7 IS NULL OR (octet_length("vnc_credentials"."kerberos_service"->'components'->>7) BETWEEN 1 AND 255 AND "vnc_credentials"."kerberos_service"->'components'->>7 !~ '[[:cntrl:]]')) AND (coalesce(octet_length("vnc_credentials"."kerberos_service"->>'realm'), 0) + coalesce(octet_length("vnc_credentials"."kerberos_service"->'components'->>0), 0) + coalesce(octet_length("vnc_credentials"."kerberos_service"->'components'->>1), 0) + coalesce(octet_length("vnc_credentials"."kerberos_service"->'components'->>2), 0) + coalesce(octet_length("vnc_credentials"."kerberos_service"->'components'->>3), 0) + coalesce(octet_length("vnc_credentials"."kerberos_service"->'components'->>4), 0) + coalesce(octet_length("vnc_credentials"."kerberos_service"->'components'->>5), 0) + coalesce(octet_length("vnc_credentials"."kerberos_service"->'components'->>6), 0) + coalesce(octet_length("vnc_credentials"."kerberos_service"->'components'->>7), 0)) <= 1024
      AND jsonb_array_length("vnc_credentials"."kerberos_service"->'components') = 2 AND "vnc_credentials"."kerberos_service"->'components'->>0 = 'vnc')
    ELSE false END);--> statement-breakpoint
ALTER TABLE "vnc_credentials" ADD CONSTRAINT "chk_vnc_credentials_kerberos" CHECK (CASE
        WHEN "vnc_credentials"."auth_method" = 'qemu_kerberos_ticket' THEN
          "vnc_credentials"."encrypted_kerberos_credential" IS NOT NULL AND char_length("vnc_credentials"."encrypted_kerberos_credential") > 0
          AND "vnc_credentials"."kerberos_initiator" IS NOT NULL AND "vnc_credentials"."kerberos_service" IS NOT NULL
          AND "vnc_credentials"."kerberos_initiator"->>'realm' = "vnc_credentials"."kerberos_service"->>'realm'
          AND "vnc_credentials"."kerberos_declared_expires_at" IS NOT NULL AND "vnc_credentials"."kerberos_declared_expires_at" > 0
        WHEN "vnc_credentials"."auth_method" IN ('qemu_kerberos_keytab', 'qemu_kerberos_password') THEN
          "vnc_credentials"."encrypted_kerberos_credential" IS NOT NULL AND char_length("vnc_credentials"."encrypted_kerberos_credential") > 0
          AND "vnc_credentials"."kerberos_initiator" IS NOT NULL AND "vnc_credentials"."kerberos_service" IS NULL AND "vnc_credentials"."kerberos_declared_expires_at" IS NULL
        ELSE "vnc_credentials"."encrypted_kerberos_credential" IS NULL AND "vnc_credentials"."kerberos_initiator" IS NULL
          AND "vnc_credentials"."kerberos_service" IS NULL AND "vnc_credentials"."kerberos_declared_expires_at" IS NULL END);--> statement-breakpoint
ALTER TABLE "vnc_credentials" ADD CONSTRAINT "chk_vnc_credentials_auth" CHECK (("vnc_credentials"."auth_method" IN ('qemu_kerberos_ticket', 'qemu_kerberos_keytab', 'qemu_kerberos_password') AND "vnc_credentials"."username" IS NULL) OR ("vnc_credentials"."auth_method" = 'rsa_aes_password' AND "vnc_credentials"."username" IS NULL) OR ("vnc_credentials"."auth_method" = 'rsa_aes_username_password' AND "vnc_credentials"."username" IS NOT NULL AND octet_length("vnc_credentials"."username") BETWEEN 1 AND 255) OR ("vnc_credentials"."auth_method" IN ('client_certificate', 'client_certificate_vnc_password') AND "vnc_credentials"."username" IS NULL) OR ("vnc_credentials"."auth_method" = 'vnc_password' AND "vnc_credentials"."username" IS NULL) OR ("vnc_credentials"."auth_method" = 'username_password' AND "vnc_credentials"."username" IS NOT NULL AND octet_length("vnc_credentials"."username") BETWEEN 1 AND 255) OR ("vnc_credentials"."auth_method" = 'qemu_scram_sha256' AND "vnc_credentials"."username" IS NOT NULL AND octet_length("vnc_credentials"."username") BETWEEN 1 AND 255 AND "vnc_credentials"."username" COLLATE "C" ~ '^[!-~]+$' AND "vnc_credentials"."username" !~ '[=,]') OR ("vnc_credentials"."auth_method" = 'apple_dh_username_password' AND "vnc_credentials"."username" IS NOT NULL AND octet_length("vnc_credentials"."username") BETWEEN 1 AND 63) OR ("vnc_credentials"."auth_method" = 'apple_srp_username_password' AND "vnc_credentials"."username" IS NOT NULL AND octet_length("vnc_credentials"."username") BETWEEN 1 AND 255) OR ("vnc_credentials"."auth_method" = 'apple_rsa_srp_username_password' AND "vnc_credentials"."username" IS NOT NULL AND octet_length("vnc_credentials"."username") BETWEEN 1 AND 234));--> statement-breakpoint
ALTER TABLE "vnc_credentials" ADD CONSTRAINT "chk_vnc_credentials_password" CHECK (("vnc_credentials"."auth_method" IN ('qemu_kerberos_ticket', 'qemu_kerberos_keytab', 'qemu_kerberos_password') AND "vnc_credentials"."encrypted_password" IS NULL AND "vnc_credentials"."encrypted_client_identity" IS NULL) OR ("vnc_credentials"."auth_method" = 'client_certificate' AND "vnc_credentials"."encrypted_password" IS NULL AND "vnc_credentials"."encrypted_client_identity" IS NOT NULL AND char_length("vnc_credentials"."encrypted_client_identity") > 0) OR ("vnc_credentials"."auth_method" = 'client_certificate_vnc_password' AND "vnc_credentials"."encrypted_password" IS NOT NULL AND char_length("vnc_credentials"."encrypted_password") > 0 AND "vnc_credentials"."encrypted_client_identity" IS NOT NULL AND char_length("vnc_credentials"."encrypted_client_identity") > 0) OR ("vnc_credentials"."auth_method" NOT IN ('client_certificate', 'client_certificate_vnc_password', 'qemu_kerberos_ticket', 'qemu_kerberos_keytab', 'qemu_kerberos_password') AND "vnc_credentials"."encrypted_password" IS NOT NULL AND char_length("vnc_credentials"."encrypted_password") > 0 AND "vnc_credentials"."encrypted_client_identity" IS NULL));