import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { z } from "zod";
import { type SwiftConstantBinding, swiftConstantBindings } from "./constants";
import { type SwiftRouteBinding, swiftRouteBindings } from "./routes";
import { type SwiftTypeBinding, swiftTypeBindings } from "./types";

export const generatedSwiftDirectory = fileURLToPath(
  new URL("../../../../../desktop/Okou/Core/Generated/", import.meta.url),
);

type JsonObject = Readonly<Record<string, unknown>>;

interface RenderContext {
  readonly label: string;
  readonly root: JsonObject;
}

interface ResolvedType {
  /** Swift type expression without the optional marker. */
  readonly swiftType: string;
  /** Whether the contract allows `null` for this value. */
  readonly nullable: boolean;
  /** Nested declarations the parent scope must emit before using `swiftType`. */
  readonly declarations: readonly string[];
}

interface TaggedUnion {
  readonly tag: string;
  readonly variants: readonly TaggedUnionVariant[];
}

interface TaggedUnionVariant {
  readonly value: string;
  readonly properties: JsonObject;
  readonly required: ReadonlySet<string>;
}

const headerLines = [
  "// @generated by @okouai/api-contracts.",
  "// Do not edit by hand.",
  "// Regenerate with: cd turbo && pnpm -F @okouai/api-contracts generate:swift",
  "",
  "import Foundation",
  "",
] as const;

const swiftIdentifierPattern = /^[A-Za-z_][A-Za-z0-9_]*$/u;
const swiftTypeNamePattern = /^[A-Z][A-Za-z0-9]*$/u;
const swiftKeywords = new Set([
  "Any",
  "Self",
  "as",
  "associatedtype",
  "break",
  "case",
  "catch",
  "class",
  "continue",
  "default",
  "defer",
  "deinit",
  "do",
  "else",
  "enum",
  "extension",
  "fallthrough",
  "false",
  "fileprivate",
  "for",
  "func",
  "guard",
  "if",
  "import",
  "in",
  "init",
  "inout",
  "internal",
  "is",
  "let",
  "nil",
  "open",
  "operator",
  "private",
  "precedencegroup",
  "protocol",
  "public",
  "repeat",
  "rethrows",
  "return",
  "self",
  "static",
  "struct",
  "subscript",
  "super",
  "switch",
  "throw",
  "throws",
  "true",
  "try",
  "typealias",
  "var",
  "where",
  "while",
]);
/** Nested type names that would shadow standard library or Codable names. */
const shadowingTypeNames = new Set([
  "Array",
  "Bool",
  "Codable",
  "CodingKeys",
  "Decodable",
  "Decoder",
  "Dictionary",
  "Double",
  "Encodable",
  "Encoder",
  "Equatable",
  "Error",
  "Hashable",
  "Int",
  "Optional",
  "Result",
  "Self",
  "Sendable",
  "String",
  "Type",
]);

function isJsonObject(value: unknown): value is JsonObject {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function toJsonSchema(schema: z.ZodType, label: string): JsonObject {
  const json: unknown = z.toJSONSchema(schema);
  if (!isJsonObject(json)) {
    throw new Error(`${label} did not produce a JSON schema object`);
  }
  return json;
}

function swiftIdentifier(name: string, label: string): string {
  if (!swiftIdentifierPattern.test(name)) {
    throw new Error(`${label} uses an unsupported Swift identifier: ${name}`);
  }
  return swiftKeywords.has(name) ? `\`${name}\`` : name;
}

function words(value: string): readonly string[] {
  return value
    .split(/[^A-Za-z0-9]+/u)
    .flatMap((part) => {
      return part.split(/(?<=[a-z0-9])(?=[A-Z])/u);
    })
    .filter((part) => {
      return part.length > 0;
    });
}

function camelCase(value: string, label: string): string {
  const parts = words(value);
  if (parts.length === 0) {
    throw new Error(`${label} cannot derive a Swift name from "${value}"`);
  }
  const [first, ...rest] = parts;
  if (first === undefined) {
    throw new Error(`${label} cannot derive a Swift name from "${value}"`);
  }
  const name = [
    first.toLowerCase(),
    ...rest.map((part) => {
      return part.charAt(0).toUpperCase() + part.slice(1).toLowerCase();
    }),
  ].join("");
  return /^[0-9]/u.test(name) ? `value${name}` : name;
}

function pascalCase(value: string, label: string): string {
  const name = camelCase(value, label);
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function nestedTypeName(propertyName: string, label: string): string {
  const name = pascalCase(propertyName, label);
  return shadowingTypeNames.has(name) ? `${name}Value` : name;
}

function swiftStringLiteral(value: string): string {
  const escaped = value
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("\n", "\\n");
  return `"${escaped}"`;
}

const maxLineWidth = 100;
/** Indentation assumed for declarations whose nesting depth is unknown at render time. */
const assumedNestedIndent = 8;

function wrapWords(text: string, width: number): readonly string[] {
  const lines: string[] = [];
  let current = "";
  for (const word of text.split(/\s+/u).filter(Boolean)) {
    if (current.length > 0 && current.length + 1 + word.length > width) {
      lines.push(current);
      current = word;
    } else {
      current = current.length === 0 ? word : `${current} ${word}`;
    }
  }
  if (current.length > 0) {
    lines.push(current);
  }
  return lines;
}

function docLines(doc: readonly string[]): readonly string[] {
  return doc.flatMap((line) => {
    return wrapWords(line, maxLineWidth - 4).map((wrapped) => {
      return `/// ${wrapped}`;
    });
  });
}

/** Renders `prefix(a, b)suffix` on one line, or one argument per line when too wide. */
function wrapArguments(
  prefix: string,
  parameters: readonly string[],
  suffix: string,
  indentWidth: number,
): readonly string[] {
  const single = `${prefix}${parameters.join(", ")}${suffix}`;
  if (single.length + indentWidth <= maxLineWidth) {
    return [single];
  }
  const continuation = `  ${parameters.join(", ")}`;
  if (continuation.length + indentWidth <= maxLineWidth) {
    return [prefix, continuation, suffix];
  }
  return [
    prefix,
    ...parameters.map((parameter, index) => {
      return `  ${parameter}${index === parameters.length - 1 ? "" : ","}`;
    }),
    suffix,
  ];
}

function indent(lines: readonly string[], level: number): readonly string[] {
  const prefix = "  ".repeat(level);
  return lines.map((line) => {
    return line.length === 0 ? line : `${prefix}${line}`;
  });
}

function joinDeclarations(
  declarations: readonly (readonly string[])[],
): readonly string[] {
  const lines: string[] = [];
  for (const declaration of declarations) {
    if (declaration.length === 0) {
      continue;
    }
    if (lines.length > 0) {
      lines.push("");
    }
    lines.push(...declaration);
  }
  return lines;
}

function resolveRef(
  schema: JsonObject,
  context: RenderContext,
  path: string,
): JsonObject {
  const ref = schema.$ref;
  if (ref === undefined) {
    return schema;
  }
  if (typeof ref !== "string" || !ref.startsWith("#/$defs/")) {
    throw new Error(`${context.label}.${path} uses an unsupported $ref`);
  }
  const definitions = context.root.$defs;
  const target = isJsonObject(definitions)
    ? definitions[ref.slice("#/$defs/".length)]
    : undefined;
  if (!isJsonObject(target)) {
    throw new Error(`${context.label}.${path} references a missing $def`);
  }
  return resolveRef(target, context, path);
}

function unwrapNullable(
  schema: JsonObject,
  context: RenderContext,
  path: string,
): JsonObject | null {
  if (Array.isArray(schema.type)) {
    const types = schema.type.filter((entry): entry is string => {
      return typeof entry === "string";
    });
    const nonNull = types.filter((entry) => {
      return entry !== "null";
    });
    const [only] = nonNull;
    if (only !== undefined && nonNull.length === 1 && types.includes("null")) {
      return { ...schema, type: only };
    }
    throw new Error(`${context.label}.${path} uses an unsupported type array`);
  }
  const alternatives = schema.anyOf ?? schema.oneOf;
  if (!Array.isArray(alternatives)) {
    return null;
  }
  const entries = alternatives.filter(isJsonObject);
  if (entries.length !== alternatives.length) {
    throw new Error(`${context.label}.${path} uses a malformed union`);
  }
  const nulls = entries.filter((entry) => {
    return entry.type === "null";
  });
  const values = entries.filter((entry) => {
    return entry.type !== "null";
  });
  const [value] = values;
  if (nulls.length === 1 && value !== undefined && values.length === 1) {
    return resolveRef(value, context, path);
  }
  return null;
}

function taggedUnion(
  schema: JsonObject,
  context: RenderContext,
  path: string,
): TaggedUnion | null {
  const alternatives = schema.oneOf ?? schema.anyOf;
  if (!Array.isArray(alternatives) || alternatives.length === 0) {
    return null;
  }
  const variants = alternatives.map((entry) => {
    const resolved = isJsonObject(entry)
      ? resolveRef(entry, context, path)
      : null;
    if (resolved === null || !isJsonObject(resolved.properties)) {
      throw new Error(`${context.label}.${path} uses an unsupported union`);
    }
    return { schema: resolved, properties: resolved.properties };
  });
  const [first] = variants;
  if (first === undefined) {
    return null;
  }
  const tag = Object.keys(first.properties).find((key) => {
    return variants.every((variant) => {
      const property = variant.properties[key];
      return isJsonObject(property) && typeof property.const === "string";
    });
  });
  if (tag === undefined) {
    throw new Error(
      `${context.label}.${path} union has no string discriminator`,
    );
  }
  return {
    tag,
    variants: variants.map(({ schema: variant, properties }) => {
      const tagSchema = properties[tag];
      const value =
        isJsonObject(tagSchema) && typeof tagSchema.const === "string"
          ? tagSchema.const
          : "";
      const rest = Object.fromEntries(
        Object.entries(properties).filter(([key]) => {
          return key !== tag;
        }),
      );
      return {
        value,
        properties: rest,
        required: new Set(
          requiredNames(variant).filter((name) => {
            return name !== tag;
          }),
        ),
      };
    }),
  };
}

function requiredNames(schema: JsonObject): readonly string[] {
  return Array.isArray(schema.required)
    ? schema.required.filter((entry): entry is string => {
        return typeof entry === "string";
      })
    : [];
}

function stringEnum(schema: JsonObject): readonly string[] | null {
  if (!Array.isArray(schema.enum)) {
    return null;
  }
  const values = schema.enum.filter((entry): entry is string => {
    return typeof entry === "string";
  });
  if (values.length !== schema.enum.length) {
    return null;
  }
  return values;
}

function constType(
  value: unknown,
  context: RenderContext,
  path: string,
): string {
  switch (typeof value) {
    case "string":
      return "String";
    case "boolean":
      return "Bool";
    case "number":
      return Number.isInteger(value) ? "Int" : "Double";
    default:
      throw new Error(`${context.label}.${path} uses an unsupported const`);
  }
}

function optionalMarker(resolved: ResolvedType, optional: boolean): string {
  return optional || resolved.nullable
    ? `${resolved.swiftType}?`
    : resolved.swiftType;
}

function primitive(swiftType: string): ResolvedType {
  return { swiftType, nullable: false, declarations: [] };
}

function resolveType(
  rawSchema: JsonObject,
  typeName: string,
  context: RenderContext,
  path: string,
): ResolvedType {
  const schema = resolveRef(rawSchema, context, path);
  const nullable = unwrapNullable(schema, context, path);
  if (nullable !== null) {
    return {
      ...resolveType(nullable, typeName, context, path),
      nullable: true,
    };
  }
  const union = taggedUnion(schema, context, path);
  if (union !== null) {
    return {
      swiftType: typeName,
      nullable: false,
      declarations: renderTaggedEnum(union, typeName, [], context, path),
    };
  }
  const enumValues = stringEnum(schema);
  if (enumValues !== null) {
    return {
      swiftType: typeName,
      nullable: false,
      declarations: renderExtensibleEnum(enumValues, typeName, context, path),
    };
  }
  if ("const" in schema) {
    return primitive(constType(schema.const, context, path));
  }
  switch (schema.type) {
    case "object":
      return resolveObject(schema, typeName, context, path);
    case "array": {
      if (!isJsonObject(schema.items)) {
        throw new Error(`${context.label}.${path} array is missing items`);
      }
      const item = resolveType(
        schema.items,
        `${typeName}Element`,
        context,
        `${path}[]`,
      );
      return {
        swiftType: `[${optionalMarker(item, false)}]`,
        nullable: false,
        declarations: item.declarations,
      };
    }
    case "string":
      return primitive("String");
    case "boolean":
      return primitive("Bool");
    case "integer":
      return primitive("Int");
    case "number":
      return primitive("Double");
    case undefined: {
      const keys = Object.keys(schema).filter((key) => {
        return key !== "$schema";
      });
      if (keys.length === 0) {
        return primitive("JSONValue");
      }
      throw new Error(`${context.label}.${path} uses an unsupported schema`);
    }
    default:
      throw new Error(
        `${context.label}.${path} uses an unsupported JSON schema type: ${String(schema.type)}`,
      );
  }
}

function resolveObject(
  schema: JsonObject,
  typeName: string,
  context: RenderContext,
  path: string,
): ResolvedType {
  if (isJsonObject(schema.properties)) {
    return {
      swiftType: typeName,
      nullable: false,
      declarations: renderStruct(
        schema.properties,
        new Set(requiredNames(schema)),
        typeName,
        [],
        new Map(),
        context,
        path,
      ),
    };
  }
  const additional = schema.additionalProperties;
  if (isJsonObject(additional) && Object.keys(additional).length > 0) {
    const value = resolveType(
      additional,
      `${typeName}Value`,
      context,
      `${path}.*`,
    );
    return {
      swiftType: `[String: ${optionalMarker(value, false)}]`,
      nullable: false,
      declarations: value.declarations,
    };
  }
  return primitive("[String: JSONValue]");
}

function renderStruct(
  properties: JsonObject,
  required: ReadonlySet<string>,
  typeName: string,
  doc: readonly string[],
  optionalFields: ReadonlyMap<string, string>,
  context: RenderContext,
  path: string,
): readonly string[] {
  if (!swiftTypeNamePattern.test(typeName)) {
    throw new Error(
      `${context.label}.${path} has an invalid Swift type name: ${typeName}`,
    );
  }
  for (const field of optionalFields.keys()) {
    if (!(field in properties)) {
      throw new Error(
        `${context.label}.${path} marks unknown field optional: ${field}`,
      );
    }
  }
  const nested: (readonly string[])[] = [];
  const nestedNames = new Set<string>();
  const fields: string[] = [];
  const parameters: string[] = [];
  const assignments: string[] = [];
  for (const [wireName, propertySchema] of Object.entries(properties)) {
    if (!isJsonObject(propertySchema)) {
      throw new Error(`${context.label}.${path}.${wireName} is malformed`);
    }
    const name = swiftIdentifier(wireName, `${context.label}.${path}`);
    const nestedName = nestedTypeName(wireName, `${context.label}.${path}`);
    const resolved = resolveType(
      propertySchema,
      nestedName,
      context,
      `${path}.${wireName}`,
    );
    if (resolved.declarations.length > 0) {
      if (nestedNames.has(nestedName)) {
        throw new Error(
          `${context.label}.${path} declares ${nestedName} twice`,
        );
      }
      nestedNames.add(nestedName);
      nested.push(resolved.declarations);
    }
    const override = optionalFields.get(wireName);
    const swiftType = optionalMarker(
      resolved,
      !required.has(wireName) || override !== undefined,
    );
    if (override !== undefined) {
      fields.push(...docLines([override]));
    }
    fields.push(`public let ${name}: ${swiftType}`);
    parameters.push(`${name}: ${swiftType}`);
    assignments.push(`self.${name} = ${name}`);
  }
  const body: string[] = [];
  const nestedLines = joinDeclarations(nested);
  if (nestedLines.length > 0) {
    body.push(...nestedLines, "");
  }
  body.push(...fields);
  if (parameters.length === 0) {
    body.push("public init() {}");
  } else {
    body.push(
      "",
      ...wrapArguments("public init(", parameters, ") {", assumedNestedIndent),
      ...indent(assignments, 1),
      "}",
    );
  }
  return [
    ...docLines(doc),
    `public struct ${typeName}: Codable, Equatable, Sendable {`,
    ...indent(body, 1),
    "}",
  ];
}

function renderExtensibleEnum(
  values: readonly string[],
  typeName: string,
  context: RenderContext,
  path: string,
): readonly string[] {
  if (!swiftTypeNamePattern.test(typeName)) {
    throw new Error(
      `${context.label}.${path} has an invalid Swift type name: ${typeName}`,
    );
  }
  const seen = new Set<string>();
  const constants = values.map((value) => {
    const name = swiftIdentifier(
      camelCase(value, `${context.label}.${path}`),
      `${context.label}.${path}`,
    );
    if (seen.has(name)) {
      throw new Error(`${context.label}.${path} maps two values to ${name}`);
    }
    seen.add(name);
    return { name, value };
  });
  return [
    "/// Known wire values are constants; unknown values decode with their raw string.",
    `public struct ${typeName}: RawRepresentable, Codable, Hashable, Sendable {`,
    "  public let rawValue: String",
    "",
    "  public init(rawValue: String) {",
    "    self.rawValue = rawValue",
    "  }",
    "",
    ...constants.flatMap(({ name, value }) => {
      const single = `  public static let ${name} = Self(rawValue: ${swiftStringLiteral(value)})`;
      return single.length + assumedNestedIndent <= maxLineWidth
        ? [single]
        : [
            `  public static let ${name} = Self(`,
            `    rawValue: ${swiftStringLiteral(value)})`,
          ];
    }),
    "",
    "  /// Every value the contract declared when this file was generated.",
    `  public static let knownValues: [${typeName}] = [`,
    ...constants.map(({ name }) => {
      return `    .${name},`;
    }),
    "  ]",
    "}",
  ];
}

function renderTaggedEnum(
  union: TaggedUnion,
  typeName: string,
  doc: readonly string[],
  context: RenderContext,
  path: string,
): readonly string[] {
  if (!swiftTypeNamePattern.test(typeName)) {
    throw new Error(
      `${context.label}.${path} has an invalid Swift type name: ${typeName}`,
    );
  }
  const label = `${context.label}.${path}`;
  const tagKey = swiftIdentifier(union.tag, label);
  const nested: (readonly string[])[] = [];
  const codingKeys = new Map<string, string>([[union.tag, tagKey]]);
  const cases: string[] = [];
  const decodeCases: string[] = [];
  const encodeCases: string[] = [];
  const seenCases = new Set<string>();
  for (const variant of union.variants) {
    const caseName = swiftIdentifier(camelCase(variant.value, label), label);
    if (seenCases.has(caseName)) {
      throw new Error(`${label} maps two variants to ${caseName}`);
    }
    seenCases.add(caseName);
    const literal = swiftStringLiteral(variant.value);
    const fieldNames = Object.keys(variant.properties);
    if (fieldNames.length === 0) {
      cases.push(`case ${caseName}`);
      decodeCases.push(`case ${literal}:`, `  self = .${caseName}`);
      encodeCases.push(
        `case .${caseName}:`,
        `  try container.encode(${literal}, forKey: .${tagKey})`,
      );
      continue;
    }
    const [wireName] = fieldNames;
    if (fieldNames.length === 1 && wireName !== undefined) {
      const propertySchema = variant.properties[wireName];
      if (!isJsonObject(propertySchema)) {
        throw new Error(`${label}.${wireName} is malformed`);
      }
      const nestedName = nestedTypeName(wireName, label);
      const resolved = resolveType(
        propertySchema,
        nestedName,
        context,
        `${path}.${wireName}`,
      );
      if (resolved.declarations.length > 0) {
        nested.push(resolved.declarations);
      }
      const key = swiftIdentifier(wireName, label);
      codingKeys.set(wireName, key);
      const optional = !variant.required.has(wireName);
      const swiftType = optionalMarker(resolved, optional);
      const decode = optional
        ? `try container.decodeIfPresent(${resolved.swiftType}.self, forKey: .${key})`
        : `try container.decode(${resolved.swiftType}.self, forKey: .${key})`;
      cases.push(`case ${caseName}(${swiftType})`);
      decodeCases.push(`case ${literal}:`, `  self = .${caseName}(${decode})`);
      encodeCases.push(
        `case .${caseName}(let value):`,
        `  try container.encode(${literal}, forKey: .${tagKey})`,
        optional
          ? `  try container.encodeIfPresent(value, forKey: .${key})`
          : `  try container.encode(value, forKey: .${key})`,
      );
      continue;
    }
    const payloadName = `${pascalCase(variant.value, label)}Payload`;
    nested.push(
      renderStruct(
        variant.properties,
        variant.required,
        payloadName,
        [],
        new Map(),
        context,
        `${path}.${variant.value}`,
      ),
    );
    cases.push(`case ${caseName}(${payloadName})`);
    decodeCases.push(
      `case ${literal}:`,
      `  self = .${caseName}(try ${payloadName}(from: decoder))`,
    );
    encodeCases.push(
      `case .${caseName}(let value):`,
      `  try container.encode(${literal}, forKey: .${tagKey})`,
      "  try value.encode(to: encoder)",
    );
  }
  const body: string[] = [];
  const nestedLines = joinDeclarations(nested);
  if (nestedLines.length > 0) {
    body.push(...nestedLines, "");
  }
  body.push(
    ...cases,
    "",
    "private enum CodingKeys: String, CodingKey {",
    ...[...codingKeys.entries()].map(([wireName, key]) => {
      return `  case ${key} = ${swiftStringLiteral(wireName)}`;
    }),
    "}",
    "",
    "public init(from decoder: any Decoder) throws {",
    "  let container = try decoder.container(keyedBy: CodingKeys.self)",
    `  switch try container.decode(String.self, forKey: .${tagKey}) {`,
    ...indent(decodeCases, 1),
    "  case let value:",
    "    throw DecodingError.dataCorruptedError(",
    `      forKey: .${tagKey}, in: container,`,
    `      debugDescription: "Unsupported ${union.tag}: \\(value)")`,
    "  }",
    "}",
    "",
    "public func encode(to encoder: any Encoder) throws {",
    "  var container = encoder.container(keyedBy: CodingKeys.self)",
    "  switch self {",
    ...indent(encodeCases, 1),
    "  }",
    "}",
  );
  return [
    ...docLines(doc),
    `public enum ${typeName}: Codable, Equatable, Sendable {`,
    ...indent(body, 1),
    "}",
  ];
}

function renderTypeBinding(binding: SwiftTypeBinding): readonly string[] {
  const label = `swift type binding ${binding.swiftTypeName}`;
  const root = toJsonSchema(binding.schema, label);
  const context: RenderContext = { label, root };
  const optionalFields = new Map(Object.entries(binding.optionalFields ?? {}));
  const schema = resolveRef(root, context, "$");
  const union = taggedUnion(schema, context, "$");
  if (union !== null) {
    if (optionalFields.size > 0) {
      throw new Error(`${label} cannot mark union fields optional`);
    }
    return renderTaggedEnum(
      union,
      binding.swiftTypeName,
      binding.doc,
      context,
      "$",
    );
  }
  if (schema.type !== "object" || !isJsonObject(schema.properties)) {
    throw new Error(
      `${label} must bind an object or discriminated union schema`,
    );
  }
  return renderStruct(
    schema.properties,
    new Set(requiredNames(schema)),
    binding.swiftTypeName,
    binding.doc,
    optionalFields,
    context,
    "$",
  );
}

export function renderSwiftTypes(
  bindings: readonly SwiftTypeBinding[] = swiftTypeBindings,
): string {
  const seen = new Set<string>();
  const declarations = bindings.map((binding) => {
    if (seen.has(binding.swiftTypeName)) {
      throw new Error(`duplicate Swift type binding: ${binding.swiftTypeName}`);
    }
    seen.add(binding.swiftTypeName);
    return renderTypeBinding(binding);
  });
  return `${[...headerLines, ...joinDeclarations(declarations)].join("\n")}\n`;
}

function renderConstant(binding: SwiftConstantBinding): readonly string[] {
  const label = `swift constant binding ${binding.swiftName}`;
  const name = swiftIdentifier(binding.swiftName, label);
  const literal =
    typeof binding.value === "string"
      ? swiftStringLiteral(binding.value)
      : Number.isInteger(binding.value)
        ? String(binding.value)
        : (() => {
            throw new Error(`${label} must be a string or integer`);
          })();
  return [...docLines(binding.doc), `public static let ${name} = ${literal}`];
}

export function renderSwiftConstants(
  bindings: readonly SwiftConstantBinding[] = swiftConstantBindings,
): string {
  const seen = new Set<string>();
  const members = bindings.map((binding) => {
    if (seen.has(binding.swiftName)) {
      throw new Error(`duplicate Swift constant binding: ${binding.swiftName}`);
    }
    seen.add(binding.swiftName);
    return renderConstant(binding);
  });
  return `${[
    ...headerLines,
    "/// Wire constants shared with the API contracts.",
    "public enum ApiConstants {",
    ...indent(joinDeclarations(members), 1),
    "}",
  ].join("\n")}\n`;
}

interface NormalizedRoute {
  readonly swiftName: string;
  readonly method: string;
  readonly path: string;
  readonly summary: string | null;
  readonly parameters: readonly string[];
}

function normalizeRoute(binding: SwiftRouteBinding): NormalizedRoute {
  const label = `swift route binding ${binding.swiftName}`;
  const { method, path, summary } = binding.route;
  if (typeof method !== "string" || !/^[A-Z]+$/u.test(method)) {
    throw new Error(`${label} has an invalid method`);
  }
  if (typeof path !== "string" || !path.startsWith("/")) {
    throw new Error(`${label} has an invalid path`);
  }
  if (summary !== undefined && typeof summary !== "string") {
    throw new Error(`${label} has an invalid summary`);
  }
  const parameters = path
    .split("/")
    .filter((segment) => {
      return segment.startsWith(":");
    })
    .map((segment) => {
      return segment.slice(1);
    });
  for (const parameter of parameters) {
    if (
      !swiftIdentifierPattern.test(parameter) ||
      swiftKeywords.has(parameter)
    ) {
      throw new Error(
        `${label} has an unsupported path parameter: ${parameter}`,
      );
    }
  }
  if (new Set(parameters).size !== parameters.length) {
    throw new Error(`${label} repeats a path parameter`);
  }
  return {
    swiftName: swiftIdentifier(binding.swiftName, label),
    method,
    path,
    summary: summary ?? null,
    parameters,
  };
}

/** Splits an interpolated path at `/` boundaries so every chunk fits within `width`. */
function chunkInterpolatedPath(path: string, width: number): readonly string[] {
  const chunks: string[] = [];
  let current = "";
  path.split("/").forEach((segment, index) => {
    const candidate = index === 0 ? segment : `${current}/${segment}`;
    if (index > 0 && candidate.length > width) {
      chunks.push(current);
      current = `/${segment}`;
    } else {
      current = candidate;
    }
  });
  if (current.length > 0) {
    chunks.push(current);
  }
  return chunks;
}

function renderRoute(route: NormalizedRoute): readonly string[] {
  const doc = route.summary === null ? [] : docLines([route.summary]);
  const method = swiftStringLiteral(route.method);
  if (route.parameters.length === 0) {
    return [
      ...doc,
      ...wrapArguments(
        `public static let ${route.swiftName} = ApiRoute(`,
        [`method: ${method}`, `path: ${swiftStringLiteral(route.path)}`],
        ")",
        2,
      ),
    ];
  }
  const interpolated = route.path
    .split("/")
    .map((segment) => {
      return segment.startsWith(":")
        ? `\\(pathSegment(${segment.slice(1)}))`
        : swiftStringLiteral(segment).slice(1, -1);
    })
    .join("/");
  const parameters = route.parameters.map((parameter) => {
    return `${parameter}: String`;
  });
  const [firstChunk = "", ...restChunks] = chunkInterpolatedPath(
    interpolated,
    maxLineWidth - 20,
  );
  const pathLines =
    restChunks.length === 0
      ? [`path: "${firstChunk}")`]
      : [
          `path: "${firstChunk}"`,
          ...restChunks.map((chunk, index) => {
            const suffix = index === restChunks.length - 1 ? ")" : "";
            return `  + "${chunk}"${suffix}`;
          }),
        ];
  return [
    ...doc,
    ...wrapArguments(
      `public static func ${route.swiftName}(`,
      parameters,
      ") -> ApiRoute {",
      2,
    ),
    "  ApiRoute(",
    `    method: ${method},`,
    ...indent(pathLines, 2),
    "}",
  ];
}

export function renderSwiftRoutes(
  bindings: readonly SwiftRouteBinding[] = swiftRouteBindings,
): string {
  const seen = new Set<string>();
  const routes = bindings.map((binding) => {
    const route = normalizeRoute(binding);
    if (seen.has(route.swiftName)) {
      throw new Error(`duplicate Swift route binding: ${route.swiftName}`);
    }
    seen.add(route.swiftName);
    return route;
  });
  const members = routes.map(renderRoute);
  const helper = routes.some((route) => {
    return route.parameters.length > 0;
  })
    ? [
        "private static let pathSegmentAllowed = CharacterSet.urlPathAllowed.subtracting(",
        '  CharacterSet(charactersIn: "/"))',
        "",
        "private static func pathSegment(_ value: String) -> String {",
        "  value.addingPercentEncoding(withAllowedCharacters: pathSegmentAllowed) ?? value",
        "}",
      ]
    : [];
  return `${[
    ...headerLines,
    "/// An API route as declared by the contract: the HTTP method and the absolute path.",
    "public struct ApiRoute: Equatable, Sendable {",
    "  public let method: String",
    "  public let path: String",
    "",
    "  public init(method: String, path: String) {",
    "    self.method = method",
    "    self.path = path",
    "  }",
    "}",
    "",
    "/// Routes the Desktop app calls. Path parameters are percent-encoded as single segments.",
    "public enum ApiRoutes {",
    ...indent(joinDeclarations([...members, helper]), 1),
    "}",
  ].join("\n")}\n`;
}

export async function generateSwiftBindings(
  outputDirectory = generatedSwiftDirectory,
): Promise<void> {
  await mkdir(outputDirectory, { recursive: true });
  await writeFile(
    join(outputDirectory, "ApiConstants.swift"),
    renderSwiftConstants(),
  );
  await writeFile(
    join(outputDirectory, "ApiRoutes.swift"),
    renderSwiftRoutes(),
  );
  await writeFile(join(outputDirectory, "ApiTypes.swift"), renderSwiftTypes());
}

function isMainModule(): boolean {
  const entrypoint = process.argv[1];
  return (
    entrypoint !== undefined &&
    import.meta.url === pathToFileURL(entrypoint).href
  );
}

if (isMainModule()) {
  void generateSwiftBindings().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
