#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

fail() {
  echo "FAIL: $1" >&2
  exit 1
}

digest_value() {
  local repo=$1 target=$2 revision=${3:-HEAD}
  RUNNER_BINARY_GIT_REVISION="$revision" \
    "${repo}/.github/scripts/runner-binary-build/digest.sh" "$target" \
    | sed -n 's/^binary-input-digest=//p'
}

commit_all() {
  local repo=$1 message=$2
  git -C "$repo" add --all
  git -C "$repo" commit -qm "$message"
}

assert_text_change_affects_digest() {
  local repo=$1 path=$2 label=$3 before after
  before=$(digest_value "$repo" aarch64-unknown-linux-musl)
  case "$path" in
    *.rs) printf '\n// %s\n' "$label" >> "${repo}/${path}" ;;
    *) printf '\n# %s\n' "$label" >> "${repo}/${path}" ;;
  esac
  git -C "$repo" add -- "$path"
  git -C "$repo" commit -qm "$label"
  after=$(digest_value "$repo" aarch64-unknown-linux-musl)
  [ "$after" != "$before" ] || fail "${label} must affect the input digest"
}

repo="${TMPDIR}/repo"
mkdir -p \
  "${repo}/.github/scripts" \
  "${repo}/crates/.cargo" \
  "${repo}/crates/guest-one/src" \
  "${repo}/crates/guest-one/tests" \
  "${repo}/crates/guest-one/examples" \
  "${repo}/crates/guest-one/benches" \
  "${repo}/crates/guest-one/fixtures" \
  "${repo}/crates/runner/src" \
  "${repo}/crates/runner/tests" \
  "${repo}/crates/runner/mitm-addon/src" \
  "${repo}/crates/runner/mitm-addon/tests" \
  "${repo}/crates/runner/scripts" \
  "${repo}/crates/other-one/src" \
  "${repo}/crates/other-one/src/feature/tests" \
  "${repo}/crates/other-one/tests" \
  "${TMPDIR}/bin"
cp -a \
  "${REPO_ROOT}/.github/scripts/runner-binary-build" \
  "${repo}/.github/scripts/runner-binary-build"
mkdir -p "${repo}/.github/scripts/runner-binary-build/tests"
printf 'build contract fixture\n' \
  > "${repo}/.github/scripts/runner-binary-build/tests/fixture.txt"

cat > "${repo}/crates/runner/guest-binaries.json" <<'JSON'
[
  {
    "package": "guest-one",
    "binary": "guest-one",
    "pathEnv": "GUEST_ONE_PATH",
    "bundledEnv": "BUNDLED_GUEST_ONE",
    "destination": "/usr/local/bin/guest-one"
  }
]
JSON
cat > "${repo}/crates/Cargo.toml" <<'TOML'
[workspace]
resolver = "2"
members = ["guest-one", "other-one", "runner"]
TOML
cat > "${repo}/crates/Cargo.lock" <<'TOML'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "guest-one"
version = "0.1.0"

[[package]]
name = "runner"
version = "0.1.0"
dependencies = [
 "guest-one",
]

[[package]]
name = "other-one"
version = "0.1.0"
TOML
cat > "${repo}/crates/guest-one/Cargo.toml" <<'TOML'
[package]
name = "guest-one"
version = "0.1.0"
edition = "2021"
TOML
cat > "${repo}/crates/runner/Cargo.toml" <<'TOML'
[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
guest-one = { path = "../guest-one" }
TOML
cat > "${repo}/crates/other-one/Cargo.toml" <<'TOML'
[package]
name = "other-one"
version = "0.1.0"
edition = "2021"
TOML
printf '[build]\ntarget-dir = "target"\n' > "${repo}/crates/.cargo/config.toml"
printf 'pub fn guest() {}\n' > "${repo}/crates/guest-one/src/lib.rs"
printf 'fn main() {}\n' > "${repo}/crates/runner/src/main.rs"
printf 'fn main() {}\n' > "${repo}/crates/runner/build.rs"
printf 'pub fn other() {}\n' > "${repo}/crates/other-one/src/lib.rs"
printf 'pub fn additional() {}\n' > "${repo}/crates/other-one/src/additional.rs"
printf 'nested source fixture\n' > "${repo}/crates/other-one/src/feature/tests/input.txt"
printf 'guest fixture\n' > "${repo}/crates/guest-one/fixtures/input.txt"
printf 'integration test\n' > "${repo}/crates/guest-one/tests/integration.rs"
printf 'example\n' > "${repo}/crates/guest-one/examples/example.rs"
printf 'bench\n' > "${repo}/crates/guest-one/benches/bench.rs"
printf 'runner integration test\n' > "${repo}/crates/runner/tests/integration.rs"
printf 'runtime\n' > "${repo}/crates/runner/mitm-addon/src/runtime.py"
printf 'mitm test\n' > "${repo}/crates/runner/mitm-addon/tests/test_runtime.py"
printf 'other integration test\n' > "${repo}/crates/other-one/tests/integration.rs"
printf '#!/usr/bin/env bash\nexit 0\n' > "${repo}/crates/runner/scripts/tool.sh"
chmod +x "${repo}/crates/runner/scripts/tool.sh"
printf 'unrelated\n' > "${repo}/README.md"
weird_relative=$'crates/guest-one/src/odd\tname\nline.txt'
printf 'odd tracked input\n' > "${repo}/${weird_relative}"

git -C "$repo" init -q
git -C "$repo" config maintenance.auto false
git -C "$repo" config user.email test@example.com
git -C "$repo" config user.name test
commit_all "$repo" baseline
baseline_revision=$(git -C "$repo" rev-parse HEAD)

baseline=$(digest_value "$repo" aarch64-unknown-linux-musl)
[[ "$baseline" =~ ^[0-9a-f]{64}$ ]] || fail "expected a SHA-256 input digest"
x86_digest=$(digest_value "$repo" x86_64-unknown-linux-musl)
[ "$baseline" != "$x86_digest" ] || fail "target must affect the input digest"

printf 'untracked\n' > "${repo}/crates/guest-one/src/untracked.rs"
[ "$(digest_value "$repo" aarch64-unknown-linux-musl)" = "$baseline" ] \
  || fail "untracked crate files must not affect the input digest"
rm "${repo}/crates/guest-one/src/untracked.rs"

printf 'changed test\n' >> "${repo}/crates/guest-one/tests/integration.rs"
printf 'changed example\n' >> "${repo}/crates/guest-one/examples/example.rs"
printf 'changed bench\n' >> "${repo}/crates/guest-one/benches/bench.rs"
printf 'changed runner test\n' >> "${repo}/crates/runner/tests/integration.rs"
printf 'changed mitm test\n' >> "${repo}/crates/runner/mitm-addon/tests/test_runtime.py"
printf 'changed other package test\n' >> "${repo}/crates/other-one/tests/integration.rs"
printf 'changed nested source test\n' >> "${repo}/crates/other-one/src/feature/tests/input.txt"
printf 'changed unrelated\n' >> "${repo}/README.md"
commit_all "$repo" excluded-changes
[ "$(digest_value "$repo" aarch64-unknown-linux-musl)" = "$baseline" ] \
  || fail "proven non-build paths must not affect the input digest"
[ "$(digest_value "$repo" aarch64-unknown-linux-musl "$baseline_revision")" = "$baseline" ] \
  || fail "historical revisions must use their own tracked context"

assert_text_change_affects_digest \
  "$repo" "crates/guest-one/src/lib.rs" "guest-source-change"
assert_text_change_affects_digest \
  "$repo" "crates/guest-one/fixtures/input.txt" "guest-fixture-change"
assert_text_change_affects_digest \
  "$repo" "crates/runner/mitm-addon/src/runtime.py" "mitm-source-change"
assert_text_change_affects_digest \
  "$repo" "crates/runner/Cargo.toml" "runner-manifest-change"
assert_text_change_affects_digest \
  "$repo" "crates/runner/build.rs" "build-script-change"
assert_text_change_affects_digest \
  "$repo" "crates/Cargo.toml" "workspace-manifest-change"
assert_text_change_affects_digest \
  "$repo" "crates/Cargo.lock" "lockfile-change"
assert_text_change_affects_digest \
  "$repo" "crates/.cargo/config.toml" "cargo-config-change"
assert_text_change_affects_digest \
  "$repo" "crates/other-one/Cargo.toml" "other-package-manifest-change"
assert_text_change_affects_digest \
  "$repo" "crates/other-one/src/lib.rs" "other-package-entry-change"
assert_text_change_affects_digest \
  "$repo" "crates/other-one/src/additional.rs" "other-package-source-change"
assert_text_change_affects_digest \
  "$repo" ".github/scripts/runner-binary-build/contract.env" "contract-change"
assert_text_change_affects_digest \
  "$repo" ".github/scripts/runner-binary-build/tests/fixture.txt" "contract-tests-path-change"

before=$(digest_value "$repo" aarch64-unknown-linux-musl)
jq '.[0].destination = "/usr/local/bin/guest-one-v2"' \
  "${repo}/crates/runner/guest-binaries.json" > "${TMPDIR}/guest-binaries.json"
mv "${TMPDIR}/guest-binaries.json" "${repo}/crates/runner/guest-binaries.json"
commit_all "$repo" guest-inventory-change
after=$(digest_value "$repo" aarch64-unknown-linux-musl)
[ "$after" != "$before" ] || fail "guest inventory must affect the input digest"

before=$after
chmod -x "${repo}/crates/runner/scripts/tool.sh"
commit_all "$repo" executable-mode-change
after=$(digest_value "$repo" aarch64-unknown-linux-musl)
[ "$after" != "$before" ] || fail "tracked executable mode must affect the input digest"

valid_revision=$(git -C "$repo" rev-parse HEAD)

ln -s ../../README.md "${repo}/crates/guest-one/src/linked.rs"
commit_all "$repo" selected-symlink
if digest_value "$repo" aarch64-unknown-linux-musl >/dev/null 2>&1; then
  fail "included symlinks must fail closed"
fi
git -C "$repo" rm -q crates/guest-one/src/linked.rs
git -C "$repo" commit -qm remove-selected-symlink

cat > "${TMPDIR}/bin/cargo" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail
if [ "${1:-}" = "metadata" ]; then
  exit
fi

printf '%s\n' "$*" >> "$FAKE_CARGO_LOG"
target=""
profile=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --target) target=$2; shift 2 ;;
    --profile) profile=$2; shift 2 ;;
    *) shift ;;
  esac
done
[ -n "$target" ]
[ -n "$profile" ]
mkdir -p "${CARGO_TARGET_DIR}/${target}/${profile}"
printf 'guest-output\n' > "${CARGO_TARGET_DIR}/${target}/${profile}/guest-one"
printf 'runner-output\n' > "${CARGO_TARGET_DIR}/${target}/${profile}/runner"
BASH
chmod +x "${TMPDIR}/bin/cargo"

printf 'exit 99\n' > "${repo}/.github/scripts/runner-binary-build/compile.sh"
printf 'untracked again\n' > "${repo}/crates/guest-one/src/untracked.rs"
. "${repo}/.github/scripts/runner-binary-build/contract.env"
context_root="${TMPDIR}/materialized/runner-binary-build-context-aarch64-unknown-linux-musl"
build_digest=$(digest_value "$repo" aarch64-unknown-linux-musl)
PATH="${TMPDIR}/bin:${PATH}" \
FAKE_CARGO_LOG="${TMPDIR}/cargo.log" \
TARGET_TRIPLE=aarch64-unknown-linux-musl \
CARGO_TARGET_DIR="${TMPDIR}/target" \
RUNNER_BINARY_CONTEXT_ROOT="$context_root" \
RUNNER_BINARY_ACTUAL_TOOLCHAIN_IMAGE="$RUNNER_BINARY_TOOLCHAIN_IMAGE" \
RUNNER_BINARY_METADATA_PATH="${TMPDIR}/metadata.json" \
  "${repo}/.github/scripts/runner-binary-build/build.sh" build >/dev/null

[ "$(wc -l < "${TMPDIR}/cargo.log" | tr -d ' ')" -eq 2 ] \
  || fail "expected guest and runner Cargo entry points"
if [ "$(grep -c -- '--locked' "${TMPDIR}/cargo.log")" -ne 2 ]; then
  fail "every Cargo build must use the tracked lockfile"
fi
jq -e \
  --arg digest "$build_digest" \
  --arg toolchain "$RUNNER_BINARY_TOOLCHAIN_IMAGE" '
    .schemaVersion == 1 and
    .binaryInputDigest == $digest and
    .toolchainImage == $toolchain and
    .target == "aarch64-unknown-linux-musl" and
    (.guestSha256 | keys) == ["guest-one"] and
    (.runnerSizeBytes > 0)
  ' "${TMPDIR}/metadata.json" >/dev/null \
  || fail "expected fresh metadata from the extracted build contract"

[ -f "${context_root}/crates/guest-one/src/lib.rs" ] \
  || fail "expected guest package source"
[ -f "${context_root}/crates/runner/mitm-addon/src/runtime.py" ] \
  || fail "expected mitm source"
[ -f "${context_root}/crates/other-one/Cargo.toml" ] \
  || fail "expected other workspace package manifest"
[ -f "${context_root}/crates/other-one/src/lib.rs" ] \
  || fail "expected other workspace package entry"
[ -f "${context_root}/crates/other-one/src/additional.rs" ] \
  || fail "default inclusion must retain other workspace package source"
[ ! -e "${context_root}/crates/other-one/src/feature/tests/input.txt" ] \
  || fail "materialization must exclude nested tests directories"
[ -f "${context_root}/.github/scripts/runner-binary-build/tests/fixture.txt" ] \
  || fail "tests directories outside crates must remain in the build contract"
[ -f "${context_root}/${weird_relative}" ] \
  || fail "expected unusual tracked filename"
[ ! -x "${context_root}/crates/runner/scripts/tool.sh" ] \
  || fail "expected materialized executable mode to match the index"
[ ! -e "${context_root}/crates/guest-one/tests/integration.rs" ] \
  || fail "materialization must exclude package integration tests"
[ ! -e "${context_root}/crates/guest-one/examples/example.rs" ] \
  || fail "materialization must exclude examples"
[ ! -e "${context_root}/crates/guest-one/benches/bench.rs" ] \
  || fail "materialization must exclude benches"
[ ! -e "${context_root}/crates/runner/mitm-addon/tests/test_runtime.py" ] \
  || fail "materialization must exclude mitm tests"
[ ! -e "${context_root}/crates/other-one/tests/integration.rs" ] \
  || fail "materialization must exclude other package integration tests"
[ ! -e "${context_root}/crates/guest-one/src/untracked.rs" ] \
  || fail "materialization must exclude untracked crate content"
[ ! -e "${context_root}/README.md" ] \
  || fail "materialization must exclude unrelated tracked content"

historical_valid_digest=$(digest_value "$repo" aarch64-unknown-linux-musl "$valid_revision")
[ "$historical_valid_digest" = "$build_digest" ] \
  || fail "equal historical context trees must produce equal digests"
[ "$historical_valid_digest" != "$baseline" ] \
  || fail "historical revision selection must distinguish included changes"

if TARGET_TRIPLE=powerpc-unknown-linux-musl \
  "${repo}/.github/scripts/runner-binary-build/build.sh" materialize >/dev/null 2>&1; then
  fail "expected unsupported target to fail"
fi
if TARGET_TRIPLE=aarch64-unknown-linux-musl \
  RUNNER_BINARY_ACTUAL_TOOLCHAIN_IMAGE=unexpected-toolchain \
  "${repo}/.github/scripts/runner-binary-build/build.sh" build >/dev/null 2>&1; then
  fail "expected a mismatched build toolchain to fail"
fi

"${REPO_ROOT}/.github/scripts/runner-binary-build/context.sh" \
  validate-workspace "$REPO_ROOT"

actual_repo="${TMPDIR}/actual-repo"
mkdir -p "${actual_repo}/.github/scripts"
git -C "$REPO_ROOT" archive HEAD crates | tar -xf - -C "$actual_repo"
cp -a \
  "${REPO_ROOT}/.github/scripts/runner-binary-build" \
  "${actual_repo}/.github/scripts/runner-binary-build"
git -C "$actual_repo" init -q
git -C "$actual_repo" config maintenance.auto false
git -C "$actual_repo" config user.email test@example.com
git -C "$actual_repo" config user.name test
commit_all "$actual_repo" actual-workspace
actual_context="${TMPDIR}/actual-materialized/runner-binary-build-context-aarch64-unknown-linux-musl"
TARGET_TRIPLE=aarch64-unknown-linux-musl \
CARGO_TARGET_DIR="${TMPDIR}/actual-target" \
RUNNER_BINARY_CONTEXT_ROOT="$actual_context" \
  "${actual_repo}/.github/scripts/runner-binary-build/build.sh" materialize >/dev/null
"${actual_context}/.github/scripts/runner-binary-build/context.sh" \
  validate-workspace "$actual_context"
[ -f "${actual_context}/crates/runner/src/main.rs" ] \
  || fail "actual context must contain runner source"
[ -f "${actual_context}/crates/runner-executor/src/lib.rs" ] \
  || fail "actual context must contain runner-executor source"
[ -f "${actual_context}/crates/runner-executor/scripts/rootfs-usage.py" ] \
  || fail "actual context must contain runner-executor diagnostic scripts"
[ ! -e "${actual_context}/crates/runner/mitm-addon/tests" ] \
  || fail "actual context must exclude runner mitm tests"
[ ! -e "${actual_context}/crates/runner-executor/src/executor/tests" ] \
  || fail "actual context must exclude runner-executor owner tests"
[ -f "${actual_context}/crates/sandbox-mock/src/lib.rs" ] \
  || fail "actual context must retain all workspace package entries"
[ -f "${actual_context}/crates/sandbox-mock/src/call_records.rs" ] \
  || fail "actual context must retain other workspace package source"

workflow_toolchain=$(awk '
  /^  compile:$/ { in_compile = 1; next }
  in_compile && /^      image: / { sub(/^      image: /, ""); print; exit }
' "${REPO_ROOT}/.github/workflows/runner-image.yml")
. "${REPO_ROOT}/.github/scripts/runner-binary-build/contract.env"
[ "$RUNNER_BINARY_INPUT_SCHEMA_VERSION" = "6" ] \
  || fail "runner binary input schema must identify content-only CLI inputs"
[ "$workflow_toolchain" = 'ghcr.io/${{ github.repository_owner }}/vm0-toolchain-rust:20260825' ] \
  || fail "Runner Image workflow toolchain must derive its owner from GitHub context"
expected_runtime_toolchain="ghcr.io/${GITHUB_REPOSITORY_OWNER:-okou-ai}/vm0-toolchain-rust:20260825"
[ "$RUNNER_BINARY_TOOLCHAIN_IMAGE" = "$expected_runtime_toolchain" ] \
  || fail "hashed build contract must derive the same runtime toolchain owner"

# Only package bytes and the identity consumed by Runner compilation matter.
cli_package="${TMPDIR}/cli-intermediate/package.tgz"
cli_manifest="${TMPDIR}/cli-identity/install-metadata.json"
cli_manifest_base="${TMPDIR}/cli-manifest-base.json"
cli_package_copy="${TMPDIR}/cli-package-copy.tgz"
mkdir -p "$(dirname "$cli_package")" "$(dirname "$cli_manifest")"
printf 'fixture CLI package\n' > "$cli_package"
jq -n \
  --arg commit "$(git -C "$repo" rev-parse HEAD)" \
  --arg sha "$(sha256sum "$cli_package" | awk '{print $1}')" \
  --argjson size "$(stat -c '%s' "$cli_package")" '{
    version: 1,
    commitSha: $commit,
    package: {path: "package.tgz", sha256: $sha, size: $size},
    versions: {cli: "9.353.0", piAgentRuntime: "1.36.0", piSdk: "0.87.1+okou.0123456789ab"},
    sessionConstruction: {digest: ("d" * 64)}
  }' > "$cli_manifest"
cp "$cli_manifest" "$cli_manifest_base"

cli_digest_value() {
  local target=${1:-aarch64-unknown-linux-musl} revision=${2:-HEAD}
  GUEST_CLI_PATH="$cli_package" GUEST_CLI_MANIFEST_PATH="$cli_manifest" \
    digest_value "$repo" "$target" "$revision"
}

assert_cli_digest_fails() {
  local label=$1
  if cli_digest_value > "${TMPDIR}/rejected-digest" 2>/dev/null; then
    fail "$label must fail"
  fi
  [ ! -s "${TMPDIR}/rejected-digest" ] || fail "$label must not emit a digest"
}

plain_arm_digest=$(digest_value "$repo" aarch64-unknown-linux-musl)
embedded_arm_digest=$(cli_digest_value)
embedded_x86_digest=$(cli_digest_value x86_64-unknown-linux-musl)
[ "$plain_arm_digest" != "$embedded_arm_digest" ] \
  || fail "bundled and unbundled Runner inputs must have different cache digests"
[ "$embedded_arm_digest" != "$embedded_x86_digest" ] \
  || fail "architecture must remain part of the content digest"
[ "$(cli_digest_value aarch64-unknown-linux-musl "$baseline_revision")" != "$embedded_arm_digest" ] \
  || fail "historical revisions with different included inputs must invalidate reuse"
[ "$(cli_digest_value aarch64-unknown-linux-musl "$valid_revision")" = "$embedded_arm_digest" ] \
  || fail "different commits with identical included inputs must share a digest"

embedded_revision=$(git -C "$repo" rev-parse HEAD)
printf 'another unrelated change\n' >> "${repo}/README.md"
printf 'another excluded test change\n' >> "${repo}/crates/guest-one/tests/integration.rs"
# Do not stage the deliberately dirty/untracked build inputs from materialization tests.
git -C "$repo" add -- README.md crates/guest-one/tests/integration.rs
git -C "$repo" commit -qm bundled-excluded-changes
for target in aarch64-unknown-linux-musl x86_64-unknown-linux-musl; do
  [ "$(cli_digest_value "$target")" = "$(cli_digest_value "$target" "$embedded_revision")" ] \
    || fail "unrelated/excluded commit changes must preserve bundled ${target} inputs"
done
if cli_digest_value aarch64-unknown-linux-musl missing-revision >/dev/null 2>&1; then
  fail "invalid source revisions must still fail"
fi

jq '.commitSha = ("b" * 40)' "$cli_manifest_base" > "$cli_manifest"
[ "$(cli_digest_value)" = "$embedded_arm_digest" ] \
  || fail "CLI commit provenance must not affect the digest"
jq -cS . "$cli_manifest_base" > "$cli_manifest"
[ "$(cli_digest_value)" = "$embedded_arm_digest" ] \
  || fail "CLI JSON formatting and key order must not affect the digest"
jq '.createdAt = "2026-10-07T00:00:00Z" |
    .package.provenance = "unused" | .versions.note = "unused" |
    .sessionConstruction.note = "unused"' "$cli_manifest_base" > "$cli_manifest"
[ "$(cli_digest_value)" = "$embedded_arm_digest" ] \
  || fail "unconsumed CLI metadata must not affect the digest"
cli_manifest_compact=$(jq -c . "$cli_manifest_base")
for unused in \
  '"unused":1.25' \
  '"unused":1,"unused":2' \
  '"unused":{"cli":1,"cli":2}' \
  '"commitSha":"first","commitSha":"second"'; do
  printf '%s,%s}\n' "${cli_manifest_compact%?}" "$unused" > "$cli_manifest"
  [ "$(cli_digest_value)" = "$embedded_arm_digest" ] \
    || fail "valid ignored JSON metadata must not affect the digest: ${unused}"
done
cp "$cli_manifest_base" "$cli_manifest"

printf 'changed bytes\n' >> "$cli_package"
assert_cli_digest_fails "CLI package/manifest disagreement"
jq --arg sha "$(sha256sum "$cli_package" | awk '{print $1}')" \
  --argjson size "$(stat -c '%s' "$cli_package")" \
  '.package.sha256 = $sha | .package.size = $size' "$cli_manifest_base" > "$cli_manifest"
changed_cli_digest=$(cli_digest_value)
[ "$changed_cli_digest" != "$embedded_arm_digest" ] \
  || fail "CLI byte changes must invalidate the Runner cache digest"
cp "$cli_manifest" "$cli_manifest_base"
cp "$cli_package" "$cli_package_copy"
for mutation in \
  '.versions.cli = "9.354.0"' \
  '.versions.piAgentRuntime = "1.37.0"' \
  '.versions.piSdk = "0.87.1+okou.abcdefabcdef"' \
  '.sessionConstruction.digest = ("e" * 64)'; do
  jq "$mutation" "$cli_manifest_base" > "$cli_manifest"
  [ "$(cli_digest_value)" != "$changed_cli_digest" ] \
    || fail "compiled CLI identity change must invalidate the digest: ${mutation}"
done
cp "$cli_manifest_base" "$cli_manifest"

# A sibling manifest is irrelevant: only the explicitly supplied path counts.
printf 'wrong sibling identity\n' > "$(dirname "$cli_package")/manifest.json"
[ "$(cli_digest_value)" = "$changed_cli_digest" ] \
  || fail "a sibling manifest must not affect the explicit input digest"
for mutation in \
  '.version = 2' \
  '.version = true' \
  '.package.size = false' \
  '.package.path = "unexpected.tgz"' \
  '.package.sha256 = ("0" * 64)' \
  '.package.size = 0' \
  'del(.versions.cli)' \
  'del(.versions.piAgentRuntime)' \
  'del(.versions.piSdk)' \
  'del(.sessionConstruction.digest)' \
  '.versions.cli = "09.353.0"' \
  '.versions.cli = "9.353.0\n"' \
  '.versions.piAgentRuntime = 1' \
  '.versions.piAgentRuntime = "1.36.0\n"' \
  '.versions.piSdk = "0.87.1"' \
  '.versions.piSdk = "0.87.1+okou.0123456789ab\n"' \
  '.sessionConstruction.digest = "invalid"' \
  '.sessionConstruction.digest = ("d" * 64 + "\n")'; do
  jq "$mutation" "$cli_manifest_base" > "$cli_manifest"
  assert_cli_digest_fails "invalid CLI identity: ${mutation}"
done
# Do not let jq normalize away lexical integer types or duplicate fields.
# serde's typed CliManifest rejects these even when the last value looks valid.
cli_manifest_compact=$(jq -c . "$cli_manifest_base")
for token in 1.0 1e0 0.1e1 1.00000000000000001; do
  printf '%s\n' "${cli_manifest_compact/\"version\":1/\"version\":${token}}" > "$cli_manifest"
  assert_cli_digest_fails "non-integer CLI schema token: ${token}"
done
cli_package_size=$(stat -c '%s' "$cli_package")
for token in "${cli_package_size}.0" "${cli_package_size}e0" "${cli_package_size}.00000000000000001"; do
  printf '%s\n' "${cli_manifest_compact/\"size\":${cli_package_size}/\"size\":${token}}" > "$cli_manifest"
  assert_cli_digest_fails "non-integer CLI size token: ${token}"
done
for field in version package versions sessionConstruction path sha256 size cli piAgentRuntime piSdk digest; do
  printf '%s\n' "${cli_manifest_compact/\"${field}\":/\"${field}\":null,\"${field}\":}" > "$cli_manifest"
  assert_cli_digest_fails "duplicate consumed CLI field: ${field}"
done
printf '%s\n' "${cli_manifest_compact/\"version\":1/\"version\":1,\"version\":1}" > "$cli_manifest"
assert_cli_digest_fails "identical duplicate CLI schema fields"
printf '%s\n' "${cli_manifest_compact/\"cli\":/\"\\u0063li\":\"9.354.0\",\"cli\":}" > "$cli_manifest"
assert_cli_digest_fails "duplicate escaped CLI version field"
for constant in NaN Infinity -Infinity; do
  printf '%s,"unused":%s}\n' "${cli_manifest_compact%?}" "$constant" > "$cli_manifest"
  assert_cli_digest_fails "non-JSON numeric constant: ${constant}"
done
printf '%s,"\\ud800":0}\n' "${cli_manifest_compact%?}" > "$cli_manifest"
assert_cli_digest_fails "non-UTF-8 CLI manifest field name"
for encoding in utf-16 utf-32; do
  python3 - "$cli_manifest_base" "$cli_manifest" "$encoding" <<'PY'
import pathlib
import sys
pathlib.Path(sys.argv[2]).write_bytes(pathlib.Path(sys.argv[1]).read_text().encode(sys.argv[3]))
PY
  assert_cli_digest_fails "non-UTF-8 CLI manifest encoding: ${encoding}"
done
printf 'not JSON\n' > "$cli_manifest"
assert_cli_digest_fails "malformed CLI JSON"
cat "$cli_manifest_base" "$cli_manifest_base" > "$cli_manifest"
assert_cli_digest_fails "multiple CLI JSON documents"
: > "$cli_manifest"
assert_cli_digest_fails "empty CLI manifest"
jq '.unused = ("x" * 16384)' "$cli_manifest_base" > "$cli_manifest"
assert_cli_digest_fails "oversized CLI manifest"
rm "$cli_manifest"
ln -s "$cli_manifest_base" "$cli_manifest"
assert_cli_digest_fails "symlinked CLI manifest"
rm "$cli_manifest"
cp "$cli_manifest_base" "$cli_manifest"
: > "$cli_package"
assert_cli_digest_fails "empty CLI package"
truncate -s $((64 * 1024 * 1024 + 1)) "$cli_package"
assert_cli_digest_fails "oversized CLI package"
rm "$cli_package"
ln -s "$cli_package_copy" "$cli_package"
assert_cli_digest_fails "symlinked CLI package"
rm "$cli_package"
cp "$cli_package_copy" "$cli_package"

if GUEST_CLI_PATH="$cli_package" GUEST_CLI_MANIFEST_PATH="" \
  digest_value "$repo" aarch64-unknown-linux-musl >/dev/null 2>&1; then
  fail "package-only CLI input must fail even with a sibling manifest"
fi
if GUEST_CLI_PATH="" GUEST_CLI_MANIFEST_PATH="$cli_manifest" \
  digest_value "$repo" aarch64-unknown-linux-musl >/dev/null 2>&1; then
  fail "manifest-only CLI input must fail"
fi
rm "$cli_manifest"
assert_cli_digest_fails "explicitly provided missing CLI manifest"
cp "$cli_manifest_base" "$cli_manifest"
rm "$cli_package"
assert_cli_digest_fails "explicitly provided missing CLI package"

echo "runner-binary-build-test: ok"
