import { describe, expect, it } from "vitest";
import { z } from "zod";
import {
  generatedSwiftDirectory,
  renderSwiftConstants,
  renderSwiftRoutes,
  renderSwiftTypes,
} from "../generate";
import { swiftConstantBindings } from "../constants";
import { swiftRouteBindings } from "../routes";
import { swiftTypeBindings } from "../types";

describe("renderSwiftConstants", () => {
  it("renders string and integer constants with their docs", () => {
    const swift = renderSwiftConstants([
      {
        swiftName: "clientTypeDesktop",
        value: "Desktop",
        doc: ["Client type."],
      },
      { swiftName: "forceUpgradeStatus", value: 426, doc: [] },
    ]);
    expect(swift).toContain("// @generated by @okouai/api-contracts.");
    expect(swift).toContain(
      '  /// Client type.\n  public static let clientTypeDesktop = "Desktop"',
    );
    expect(swift).toContain("  public static let forceUpgradeStatus = 426");
  });

  it("rejects duplicate and non-integer constants", () => {
    expect(() => {
      return renderSwiftConstants([
        { swiftName: "a", value: "x", doc: [] },
        { swiftName: "a", value: "y", doc: [] },
      ]);
    }).toThrow("duplicate Swift constant binding: a");
    expect(() => {
      return renderSwiftConstants([{ swiftName: "a", value: 1.5, doc: [] }]);
    }).toThrow("must be a string or integer");
  });
});

describe("renderSwiftRoutes", () => {
  it("renders parameterless routes as values and parameterized routes as functions", () => {
    const swift = renderSwiftRoutes([
      {
        swiftName: "health",
        route: { method: "GET", path: "/api/health", summary: "Health" },
      },
      {
        swiftName: "complete",
        route: {
          method: "POST",
          path: "/api/hosts/:hostId/commands/:commandId/complete",
        },
      },
    ]);
    expect(swift).toContain(
      '  /// Health\n  public static let health = ApiRoute(method: "GET", path: "/api/health")',
    );
    expect(swift).toContain(
      "  public static func complete(hostId: String, commandId: String) -> ApiRoute {",
    );
    expect(swift).toContain(
      '"/api/hosts/\\(pathSegment(hostId))/commands/\\(pathSegment(commandId))/complete"',
    );
    expect(swift).toContain(
      "private static func pathSegment(_ value: String) -> String {",
    );
  });

  it("omits the segment encoder when no route has parameters", () => {
    const swift = renderSwiftRoutes([
      { swiftName: "health", route: { method: "GET", path: "/api/health" } },
    ]);
    expect(swift).not.toContain("pathSegment");
  });

  it("rejects invalid methods, relative paths, and keyword parameters", () => {
    expect(() => {
      return renderSwiftRoutes([
        { swiftName: "a", route: { method: "get", path: "/x" } },
      ]);
    }).toThrow("invalid method");
    expect(() => {
      return renderSwiftRoutes([
        { swiftName: "a", route: { method: "GET", path: "x" } },
      ]);
    }).toThrow("invalid path");
    expect(() => {
      return renderSwiftRoutes([
        { swiftName: "a", route: { method: "GET", path: "/x/:class" } },
      ]);
    }).toThrow("unsupported path parameter: class");
  });
});

describe("renderSwiftTypes", () => {
  it("renders structs with optional, nullable, nested, record, and unknown fields", () => {
    const swift = renderSwiftTypes([
      {
        schema: z.object({
          id: z.string().uuid(),
          count: z.number().int(),
          ratio: z.number(),
          label: z.string().nullable(),
          note: z.string().optional(),
          tags: z.array(z.string()),
          flags: z.record(z.string(), z.boolean()),
          payload: z.record(z.string(), z.unknown()),
          anything: z.unknown(),
          nested: z.object({ ok: z.literal(true) }),
          error: z.object({ message: z.string() }).optional(),
        }),
        swiftTypeName: "Sample",
        doc: ["A sample."],
      },
    ]);
    expect(swift).toContain(
      "/// A sample.\npublic struct Sample: Codable, Equatable, Sendable {",
    );
    expect(swift).toContain("  public let id: String\n");
    expect(swift).toContain("  public let count: Int\n");
    expect(swift).toContain("  public let ratio: Double\n");
    expect(swift).toContain("  public let label: String?\n");
    expect(swift).toContain("  public let note: String?\n");
    expect(swift).toContain("  public let tags: [String]\n");
    expect(swift).toContain("  public let flags: [String: Bool]\n");
    expect(swift).toContain("  public let payload: [String: JSONValue]\n");
    expect(swift).toContain("  public let anything: JSONValue\n");
    expect(swift).toContain(
      "  public struct Nested: Codable, Equatable, Sendable {\n    public let ok: Bool\n",
    );
    expect(swift).toContain(
      "  public struct ErrorValue: Codable, Equatable, Sendable {",
    );
    expect(swift).toContain("  public let error: ErrorValue?\n");
    expect(swift).toContain("  public init(\n    id: String,\n    count: Int,");
  });

  it("decodes contract-required nullable fields explicitly", () => {
    const swift = renderSwiftTypes([
      {
        schema: z.object({
          id: z.string(),
          orgId: z.string().nullable(),
          note: z.string().optional(),
        }),
        swiftTypeName: "Member",
        doc: [],
      },
    ]);
    expect(swift).toContain(
      "  public init(from decoder: any Decoder) throws {",
    );
    expect(swift).toContain(
      "    id = try container.decode(String.self, forKey: .id)",
    );
    expect(swift).toContain("    guard container.contains(.orgId) else {");
    expect(swift).toContain(
      "    orgId = try container.decodeIfPresent(String.self, forKey: .orgId)",
    );
    expect(swift).toContain(
      "    note = try container.decodeIfPresent(String.self, forKey: .note)",
    );
    expect(swift).toContain("    try container.encode(orgId, forKey: .orgId)");
    expect(swift).toContain(
      "    try container.encodeIfPresent(note, forKey: .note)",
    );
    const synthesized = renderSwiftTypes([
      {
        schema: z.object({ id: z.string(), note: z.string().optional() }),
        swiftTypeName: "Plain",
        doc: [],
      },
    ]);
    expect(synthesized).not.toContain("init(from decoder");
  });

  it("renders string enums as extensible raw-value structs", () => {
    const swift = renderSwiftTypes([
      {
        schema: z.object({
          kind: z.enum(["apps.list", "element.set_value", "default"]),
        }),
        swiftTypeName: "Command",
        doc: [],
      },
    ]);
    expect(swift).toContain(
      "  public struct Kind: RawRepresentable, Codable, Hashable, Sendable {",
    );
    expect(swift).toContain(
      '    public static let appsList = Self(rawValue: "apps.list")',
    );
    expect(swift).toContain(
      '    public static let elementSetValue = Self(rawValue: "element.set_value")',
    );
    expect(swift).toContain(
      '    public static let `default` = Self(rawValue: "default")',
    );
    expect(swift).toContain("    public static let knownValues: [Kind] = [");
  });

  it("renders discriminated unions as enums with associated values", () => {
    const swift = renderSwiftTypes([
      {
        schema: z.discriminatedUnion("status", [
          z.object({ status: z.literal("idle") }),
          z.object({
            status: z.literal("command"),
            command: z.object({ id: z.string() }),
          }),
          z.object({
            status: z.literal("failed"),
            code: z.string(),
            retry: z.boolean(),
          }),
        ]),
        swiftTypeName: "Claim",
        doc: [],
      },
    ]);
    expect(swift).toContain(
      "public enum Claim: Codable, Equatable, Sendable {",
    );
    expect(swift).toContain(
      "  case idle\n  case command(Command)\n  case failed(FailedPayload)\n",
    );
    expect(swift).toContain(
      "  public struct Command: Codable, Equatable, Sendable {",
    );
    expect(swift).toContain(
      "  public struct FailedPayload: Codable, Equatable, Sendable {",
    );
    expect(swift).toContain('    case "idle":\n      self = .idle\n');
    expect(swift).toContain(
      '    case "command":\n      self = .command(try container.decode(Command.self, forKey: .command))\n',
    );
    expect(swift).toContain(
      "      self = .failed(try FailedPayload(from: decoder))",
    );
    expect(swift).toContain(
      '    case .command(let value):\n      try container.encode("command", forKey: .status)\n      try container.encode(value, forKey: .command)\n',
    );
    expect(swift).toContain("      try value.encode(to: encoder)");
  });

  it("applies documented optional-field overrides", () => {
    const swift = renderSwiftTypes([
      {
        schema: z.object({
          hostId: z.string(),
          notifications: z.object({ name: z.string() }),
        }),
        swiftTypeName: "Registration",
        doc: [],
        optionalFields: {
          notifications: "Optional for rollout: older APIs omit it.",
        },
      },
    ]);
    expect(swift).toContain(
      "  /// Optional for rollout: older APIs omit it.\n  public let notifications: Notifications?\n",
    );
    expect(() => {
      return renderSwiftTypes([
        {
          schema: z.object({ hostId: z.string() }),
          swiftTypeName: "Registration",
          doc: [],
          optionalFields: { missing: "x" },
        },
      ]);
    }).toThrow("marks unknown field optional: missing");
  });

  it("rejects unsupported shapes", () => {
    expect(() => {
      return renderSwiftTypes([
        {
          schema: z.object({ value: z.union([z.string(), z.number()]) }),
          swiftTypeName: "A",
          doc: [],
        },
      ]);
    }).toThrow("unsupported type array");
    expect(() => {
      return renderSwiftTypes([
        {
          schema: z.object({
            value: z.union([
              z.object({ a: z.string() }),
              z.object({ b: z.number() }),
            ]),
          }),
          swiftTypeName: "A",
          doc: [],
        },
      ]);
    }).toThrow("union has no string discriminator");
    expect(() => {
      return renderSwiftTypes([
        { schema: z.string(), swiftTypeName: "A", doc: [] },
      ]);
    }).toThrow("must bind an object or discriminated union schema");
    expect(() => {
      return renderSwiftTypes([
        { schema: z.object({ a: z.string() }), swiftTypeName: "A", doc: [] },
        { schema: z.object({ b: z.string() }), swiftTypeName: "A", doc: [] },
      ]);
    }).toThrow("duplicate Swift type binding: A");
  });
});

describe("desktop bindings", () => {
  it("render the constants, routes, and types the Desktop app binds", () => {
    const constants = renderSwiftConstants(swiftConstantBindings);
    expect(constants).toContain(
      'public static let clientTypeDesktop = "Desktop"',
    );
    expect(constants).toContain(
      "public static let clientForceUpgradeStatus = 426",
    );
    expect(constants).toContain(
      'public static let apiErrorCodeConflict = "CONFLICT"',
    );

    const routes = renderSwiftRoutes(swiftRouteBindings);
    expect(routes).toContain(
      "public static func computerUseHostCommandComplete(",
    );
    expect(routes).toContain('path: "/api/desktop/compatibility"');
    expect(routes).toContain("public static func desktopProductDmgDownload(");

    const types = renderSwiftTypes(swiftTypeBindings);
    for (const name of [
      "ComputerUseHostRegistration",
      "ComputerUseHostHeartbeat",
      "ComputerUseCommandClaim",
      "DesktopUpgradeRequired",
      "DesktopCompatibilityPolicy",
      "AuthenticatedUser",
      "Organization",
      "FeatureSwitches",
      "ApiError",
    ]) {
      expect(types).toMatch(
        new RegExp(`^public (struct|enum) ${name}: `, "mu"),
      );
    }
    expect(types).toContain(
      "public let commandNotifications: CommandNotifications?",
    );
    expect(types).toContain("public let payload: [String: JSONValue]");
    expect(types).toContain("public let minimumSupportedVersion: String?");
    expect(generatedSwiftDirectory).toMatch(
      /desktop\/Okou\/Core\/Generated\/$/u,
    );
  });
});
