/**
 * Feature switch keys
 *
 * Defines all available feature switch identifiers.
 */
export enum FeatureSwitchKey {
  Dummy = "_dummy",
  AhrefsConnector = "ahrefsConnector",
  BillConnector = "billConnector",
  BentomlConnector = "bentomlConnector",
  CanvaConnector = "canvaConnector",
  CopperConnector = "copperConnector",
  DatadogConnector = "datadogConnector",
  DeelConnector = "deelConnector",
  DocuSignConnector = "docusignConnector",
  ExpensifyConnector = "expensifyConnector",
  MercuryConnector = "mercuryConnector",
  NeonConnector = "neonConnector",
  NetSuiteConnector = "netSuiteConnector",
  GarminConnectConnector = "garminConnectConnector",
  RedditConnector = "redditConnector",
  SupabaseConnector = "supabaseConnector",
  WebflowConnector = "webflowConnector",
  CloseConnector = "closeConnector",
  PayPalConnector = "payPalConnector",
  RampConnector = "rampConnector",
  ResendConnector = "resendConnector",
  SpotifyConnector = "spotifyConnector",
  OkouDebug = "_debug",
  Banking = "banking",
  Lab = "_lab",
  StripeInvoicePaidWorkflowAutomations = "stripeInvoicePaidWorkflowAutomations",
  OfficialWorkflows = "officialWorkflows",
  TestOauthConnector = "_testOauthConnector",
  FreshdeskConnector = "freshdeskConnector",
  StabilityAiConnector = "stabilityAiConnector",
  ZoomConnector = "zoomConnector",
  WorkdayConnector = "workdayConnector",
  RealAgentInPreview = "_realAgentInPreview",
  ZapierConnector = "zapierConnector",
  PrivateArtifacts = "privateArtifacts",
  ArtifactPreviews = "artifactPreviews",
  StablePreviewFullscreen = "stablePreviewFullscreen",
  SidebarSubscriptionUsage = "sidebarSubscriptionUsage",
  PwaNavigation = "pwaNavigation",
  FeishuIntegration = "_feishuIntegration",
  LarkIntegration = "larkIntegration",
  DiscordIntegration = "discordIntegration",
  VncAccess = "vncAccess",
  PiMemory = "piMemory",
  ComposerTaskChips = "composerTaskChips",
  ChatComposerLayout = "chatComposerLayout",
  ChatThreadArchiving = "chatThreadArchiving",
  ChatThreadMuting = "chatThreadMuting",
  ChatRunningIndicatorWave = "chatRunningIndicatorWave",
  ComposerAddMenu = "composerAddMenu",
  ComposerAnchoredSuggestions = "composerAnchoredSuggestions",
  CustomTemplates = "customTemplates",
  PresentationConvert = "presentationConvert",
  DeliveryFormatGuidance = "deliveryFormatGuidance",
  GoogleSlidesConversion = "googleSlidesConversion",
  BrowserNativeInput = "browserNativeInput",
  HomeTaskRecommendations = "homeTaskRecommendations",
}
