[package]
name = "runner-provider"
version = "0.3.3"
edition.workspace = true
description = "Runner API and local job-provider coordination"

[dependencies]
ably-subscriber.workspace = true
api-contracts.workspace = true
guest-contracts.workspace = true
guest-control-proto.workspace = true
process-control-ipc.workspace = true
runner-host.workspace = true
runner-types.workspace = true

async-trait.workspace = true
chrono = { workspace = true, features = ["now", "serde"] }
futures-util = { workspace = true, features = ["async-await", "async-await-macro", "sink", "std"] }
nix = { workspace = true, features = ["fs", "inotify"] }
reqwest = { workspace = true, features = ["json", "rustls"] }
hyper.workspace = true
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
serde_path_to_error.workspace = true
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-util = { workspace = true, features = ["io", "io-util", "rt"] }
tracing = { workspace = true, features = ["attributes", "std"] }
url = { workspace = true, features = ["std"] }
uuid = { workspace = true, features = ["serde", "std", "v4", "v5"] }

[dev-dependencies]
http-body.workspace = true
httpmock = { workspace = true, features = ["cookies"] }
sandbox.workspace = true
tempfile = { workspace = true, features = ["getrandom"] }
tokio = { workspace = true, features = ["process", "test-util"] }
tracing-subscriber = { workspace = true, features = ["fmt", "std"] }
tracing-test-support.workspace = true

[lints]
workspace = true
